### ISSUE TITLE
Tests use contracts which is not in tox requirements

### ISSUE THREAD

**Issue by vstinner** [coveragepy/coveragepy#1001]
When I run coverage 5.1 tests with `python3.8 -m tox -e py`, a test fails on missing `contracts` module. But this test requirement is not in tox.ini. I found COVERAGE_NO_CONTRACTS env var in the code, but it doesn't seem to be set by tox neither:

```
# Environment COVERAGE_NO_CONTRACTS=1 can turn off contracts while debugging
# tests to remove noise from stack traces.
# $set_env.py: COVERAGE_NO_CONTRACTS - Disable PyContracts to simplify stack traces.
USE_CONTRACTS = env.TESTING and not bool(int(os.environ.get("COVERAGE_NO_CONTRACTS", 0)))
```

Failing test: <tests.test_summary.SummaryTest testMethod=test_report_show_missing_branches_and_lines>

Error:

```
E       AssertionError: 'Error processing line 1 of /home/vstinner[1377 chars]ny\n' != 'x\ny\n'
E       - Error processing line 1 of /home/vstinner/myprojects/pythonci/work/cpython-3.8.3_coverage-5.1/coverage-5.1/.tox/py/lib64/python3.8/site-packages/subcover_gw1.pth:
E       - 
E       -   Traceback (most recent call last):
E       -     File "/usr/lib64/python3.8/site.py", line 169, in addpackage
E       -       exec(line)
E       -     File "<string>", line 1, in <module>
E       -     File "/home/vstinner/myprojects/pythonci/work/cpython-3.8.3_coverage-5.1/coverage-5.1/coverage/__init__.py", line 15, in <module>
E       -       from coverage.control import Coverage, process_startup
E       -     File "/home/vstinner/myprojects/pythonci/work/cpython-3.8.3_coverage-5.1/coverage-5.1/coverage/control.py", line 15, in <module>
E       -       from coverage.annotate import AnnotateReporter
E       -     File "/home/vstinner/myprojects/pythonci/work/cpython-3.8.3_coverage-5.1/coverage-5.1/coverage/annotate.py", line 10, in <module>
E       -       from coverage.files import flat_rootname
E       -     File "/home/vstinner/myprojects/pythonci/work/cpython-3.8.3_coverage-5.1/coverage-5.1/coverage/files.py", line 17, in <module>
E       -       from coverage.misc import contract, CoverageException, join_regex, isolate_module
E       -     File "/home/vstinner/myprojects/pythonci/work/cpython-3.8.3_coverage-5.1/coverage-5.1/coverage/misc.py", line 60, in <module>
E       -       from contracts import contract              # pylint: disable=unused-import
E       -   ModuleNotFoundError: No module named 'contracts'
E       - 
E       - Remainder of file ignored
E         x
E         y
```

**Comment by vstinner** [comment]
My goal is to test coverage on different Python versions with my https://github.com/vstinner/pythonci tool which creates a venv, download coverage tarball, decompress the tarball, run tests with tox.

**Comment by nedbat** [comment]
PyContracts is mentioned in requirements/pytest.pip, which is installed by tox [here](https://github.com/nedbat/coveragepy/blob/master/tox.ini#L18).

What version of tox do you have?  "python -m tox -e py" works for me with tox version 3.15.2.

**Comment by nedbat** [comment]
Feel free to re-open this if there's something I need to fix.
