### ISSUE TITLE
AttributeError: 'Coverage' object has no attribute 'source'

### ISSUE THREAD

**Issue by elfarsaouiomar** [coveragepy/coveragepy#1006]
**Describe the bug**
hi ,
it's my first time used this tools, it's a great . but i have problem when i run 
`python3 manage.py jenkins --enable-coverage`
```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/omar/git/ecommerce/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/omar/git/ecommerce/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/omar/git/ecommerce/venv/lib/python3.8/site-packages/django_jenkins/management/commands/jenkins.py", line 47, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/home/omar/git/ecommerce/venv/lib/python3.8/site-packages/django/core/management/commands/test.py", line 23, in run_from_argv
    super().run_from_argv(argv)
  File "/home/omar/git/ecommerce/venv/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/omar/git/ecommerce/venv/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/omar/git/ecommerce/venv/lib/python3.8/site-packages/django_jenkins/management/commands/jenkins.py", line 109, in handle
    tested_locations = self.get_tested_locations(test_labels)
  File "/home/omar/git/ecommerce/venv/lib/python3.8/site-packages/django_jenkins/management/commands/jenkins.py", line 135, in get_tested_locations
    elif coverage and coverage.coverage.source:
AttributeError: 'Coverage' object has no attribute 'source'
```
python version : Python 3.8.3
django version : 3.0
django_jenkins: django-jenkins==0.110.0

**Comment by nedbat** [comment]
You didn't mention what version of coverage.py you are using, but this looks like a version incompatibility between coverage.py and the Jenkins coverage support.  It looks like they are using internal unsupported interfaces in coverage.py. You should open a bug report on their bug tracker.

**Comment by elfarsaouiomar** [comment]
hi 
thank you for your response .
i use coverage version 5.1.

**Comment by nedbat** [comment]
Do you have a link to their issue tracker?

**Comment by nedbat** [comment]
Feel free to re-open this if there's something I can do.
