### ISSUE TITLE
after upgrade from 4.5.3 to latest 5.2 version i notice _sqlite3 module not found issue

### ISSUE THREAD

**Issue by farhancitrix** [coveragepy/coveragepy#1014]
**Describe the bug**
4.5.3 everything works fine but after upgraded to 5.2 i notice this error.

**To Reproduce**
root@ec2-50-17-15-170# coverage run abc.py
Traceback (most recent call last):
  File "/var/python/bin/coverage", line 11, in <module>
    load_entry_point('coverage==5.2', 'console_scripts', 'coverage')()
  File "/var/python/lib/python2.7/site-packages/setuptools-40.5.0-py2.7.egg/pkg_resources/__init__.py", line 484, in load_entry_point
  File "/var/python/lib/python2.7/site-packages/setuptools-40.5.0-py2.7.egg/pkg_resources/__init__.py", line 2725, in load_entry_point
  File "/var/python/lib/python2.7/site-packages/setuptools-40.5.0-py2.7.egg/pkg_resources/__init__.py", line 2343, in load
  File "/var/python/lib/python2.7/site-packages/setuptools-40.5.0-py2.7.egg/pkg_resources/__init__.py", line 2349, in resolve
  File "/var/python/lib/python2.7/site-packages/coverage/__init__.py", line 15, in <module>
    from coverage.control import Coverage, process_startup
  File "/var/python/lib/python2.7/site-packages/coverage/control.py", line 20, in <module>
    from coverage.data import CoverageData, combine_parallel_data
  File "/var/python/lib/python2.7/site-packages/coverage/data.py", line 17, in <module>
    from coverage.sqldata import CoverageData
  File "/var/python/lib/python2.7/site-packages/coverage/sqldata.py", line 15, in <module>
    import sqlite3
  File "/var/python/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/var/python/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3

**Additional context**
I installed pysqlint as well still same error
Same device if i install 4.5.3 version then no issue is observed

**Comment by nedbat** [comment]
Version 5 requires sqlite, which is in the standard library.  If you built your own Python, you have to make sure the sqlite development files are available.  The build output will list which modules couldn't be built.

Can you tell me more about your configuration? Where did your Python interpreter come from?

**Comment by TheCleric** [comment]
I can't speak for them, but found this same issue tonight on my machine. I am running python 3.8.3 on Windows 10 installed via Anaconda 2020.07.

**Comment by TheCleric** [comment]
Looks like (at least for me) this may be an issue with Anaconda: https://stackoverflow.com/questions/54876404/unable-to-import-sqlite3-using-anaconda-python

I'll go back to using a regular python install and trying again.

**Comment by TheCleric** [comment]
UPDATE:

Worked fine.
