### ISSUE TITLE
key error

### ISSUE THREAD

**Issue by oreginha** [coveragepy/coveragepy#1141]
C:\Users\oregi> uncompyle6
Traceback (most recent call last):
  File "c:\users\oregi\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\oregi\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\oregi\AppData\Local\Programs\Python\Python39\Scripts\uncompyle6.exe\__main__.py", line 4, in <module>
  File "c:\users\oregi\appdata\local\programs\python\python39\lib\site-packages\uncompyle6\__init__.py", line 53, in <module>
    import uncompyle6.semantics.pysource
  File "c:\users\oregi\appdata\local\programs\python\python39\lib\site-packages\uncompyle6\semantics\pysource.py", line 141, in <module>
    from uncompyle6.parsers.treenode import SyntaxTree
  File "c:\users\oregi\appdata\local\programs\python\python39\lib\site-packages\uncompyle6\parsers\treenode.py", line 3, in <module>
    from uncompyle6.scanners.tok import NoneToken
  File "c:\users\oregi\appdata\local\programs\python\python39\lib\site-packages\uncompyle6\scanners\tok.py", line 200, in <module>
    NoneToken = Token("LOAD_CONST", offset=-1, attr=None, pattr=None)
  File "c:\users\oregi\appdata\local\programs\python\python39\lib\site-packages\uncompyle6\scanners\tok.py", line 86, in __init__
    from xdis.std import _std_api
  File "c:\users\oregi\appdata\local\programs\python\python39\lib\site-packages\xdis\std.py", line 220, in <module>
    _std_api = make_std_api()
  File "c:\users\oregi\appdata\local\programs\python\python39\lib\site-packages\xdis\std.py", line 218, in make_std_api
    return _StdApi(python_version, variant)
  File "c:\users\oregi\appdata\local\programs\python\python39\lib\site-packages\xdis\std.py", line 73, in __init__
    self.opc = opc = get_opcode_module(python_version, variant)
  File "c:\users\oregi\appdata\local\programs\python\python39\lib\site-packages\xdis\op_imports.py", line 173, in get_opcode_module
    return op_imports[canonic_python_version[vers_str]]
KeyError: '3.9.4'

**Comment by nedbat** [comment]
This doesn't look like it has anything to do with coverage.py.  Are you in the right repo?  Feel free to re-open with more information if you need to.
