### ISSUE TITLE
Problem installing Coverage as a dependency

### ISSUE THREAD

**Issue by MartyMcFlyInTheSky** [coveragepy/coveragepy#1243]
I'm installing coverage as a dependency (I guess for flask?) and I get the following error:

```
Collecting flask-mongoengine==0.8.2 (from -r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/db/4d/7125aad7bac8278b857a26d88d563a6aef0291e2bfbd9fbf56329706b85a/flask-mongoengine-0.8.2.tar.gz
    Complete output from command python setup.py egg_info:
    zip_safe flag not set; analyzing archive contents...
    test_files.__pycache__.new_tests.cpython-35: module references __path__
    __pycache__.rednose.cpython-35: module references __file__

    Installed c:\users\some_user\appdata\local\temp\pip-build-7umvissg\flask-mongoengine\.eggs\rednose-1.3.0-py3.5.egg
    Searching for nose
    Reading https://pypi.python.org/simple/nose/
    Downloading https://files.pythonhosted.org/packages/58/a5/0dc93c3ec33f4e281849523a5a913fa1eea9a3068acfa754d44d88107a44/nose-1.3.7.tar.gz#sha256=f1bffef9cbc82628f6e7d7b40d7e255aefaa1adb6a1b1d26c69a8b79e6208a98
    Best match: nose 1.3.7
    Processing nose-1.3.7.tar.gz
    Writing C:\Users\some_user\AppData\Local\Temp\easy_install-jsxeppyh\nose-1.3.7\setup.cfg
    Running nose-1.3.7\setup.py -q bdist_egg --dist-dir C:\Users\some_user\AppData\Local\Temp\easy_install-jsxeppyh\nose-1.3.7\egg-dist-tmp-xtzpfapk
    no previously-included directories found matching 'doc\.build'
    creating c:\users\some_user\appdata\local\temp\pip-build-7umvissg\flask-mongoengine\.eggs\nose-1.3.7-py3.5.egg
    Extracting nose-1.3.7-py3.5.egg to c:\users\some_user\appdata\local\temp\pip-build-7umvissg\flask-mongoengine\.eggs

    Installed c:\users\some_user\appdata\local\temp\pip-build-7umvissg\flask-mongoengine\.eggs\nose-1.3.7-py3.5.egg
    Searching for coverage
    Reading https://pypi.python.org/simple/coverage/
    Downloading https://files.pythonhosted.org/packages/24/24/f95d9d306081b4265fd05eb5d2646984bfe2bb34a33fd5ff84a77605918c/coverage-6.0.2.tar.gz#sha256=6807947a09510dc31fa86f43595bf3a14017cd60bf633cc746d52141bfa6b149
    Best match: coverage 6.0.2
    Processing coverage-6.0.2.tar.gz
    Writing C:\Users\some_user\AppData\Local\Temp\easy_install-iw843ifh\coverage-6.0.2\setup.cfg
    Running coverage-6.0.2\setup.py -q bdist_egg --dist-dir C:\Users\some_user\AppData\Local\Temp\easy_install-iw843ifh\coverage-6.0.2\egg-dist-tmp-17c12i46
    Traceback (most recent call last):
      File "c:\data\some_tool\server_next\backend\env\lib\site-packages\setuptools\sandbox.py", line 157, in save_modules
        yield saved
      File "c:\data\some_tool\server_next\backend\env\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
        yield
      File "c:\data\some_tool\server_next\backend\env\lib\site-packages\setuptools\sandbox.py", line 248, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "c:\data\some_tool\server_next\backend\env\lib\site-packages\setuptools\sandbox.py", line 278, in run
        return func()
      File "c:\data\some_tool\server_next\backend\env\lib\site-packages\setuptools\sandbox.py", line 246, in runner
        _execfile(setup_script, ns)
      File "c:\data\some_tool\server_next\backend\env\lib\site-packages\setuptools\sandbox.py", line 46, in _execfile
        code = compile(script, filename, 'exec')
      File "C:\Users\some_user\AppData\Local\Temp\easy_install-iw843ifh\coverage-6.0.2\setup.py", line 116
        author=f'Ned Batchelder and {num_others} others',
                                                       ^
    SyntaxError: invalid syntax

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\some_user\AppData\Local\Temp\pip-build-7umvissg\flask-mongoengine\setup.py", line 58, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules'
      File "C:\Users\some_user\AppData\Local\Programs\Python\Python35\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\data\some_tool\server_next\backend\env\lib\site-packages\setuptools\dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "c:\data\some_tool\server_next\backend\env\lib\site-packages\setuptools\dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "c:\data\some_tool\server_next\backend\env\lib\site-packages\pkg_resources\__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "c:\data\some_tool\server_next\backend\env\lib\site-packages\pkg_resources\__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "c:\data\some_tool\server_next\backend\env\lib\site-packages\pkg_resources\__init__.py", line 1134, in obtain
        return installer(requirement)
      File "c:\data\some_tool\server_next\backend\env\lib\site-packages\setuptools\dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\data\some_tool\server_next\backend\env\lib\site-packages\setuptools\command\easy_install.py", line 665, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "c:\data\some_tool\server_next\backend\env\lib\site-packages\setuptools\command\easy_install.py", line 695, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "c:\data\some_tool\server_next\backend\env\lib\site-packages\setuptools\command\easy_install.py", line 876, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "c:\data\some_tool\server_next\backend\env\lib\site-packages\setuptools\command\easy_install.py", line 1115, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "c:\data\some_tool\server_next\backend\env\lib\site-packages\setuptools\command\easy_install.py", line 1101, in run_setup
        run_setup(setup_script, args)
      File "c:\data\some_tool\server_next\backend\env\lib\site-packages\setuptools\sandbox.py", line 251, in run_setup
        raise
      File "C:\Users\some_user\AppData\Local\Programs\Python\Python35\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\data\some_tool\server_next\backend\env\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
        yield
      File "C:\Users\some_user\AppData\Local\Programs\Python\Python35\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\data\some_tool\server_next\backend\env\lib\site-packages\setuptools\sandbox.py", line 169, in save_modules
        saved_exc.resume()
      File "c:\data\some_tool\server_next\backend\env\lib\site-packages\setuptools\sandbox.py", line 144, in resume
        six.reraise(type, exc, self._tb)
      File "c:\data\some_tool\server_next\backend\env\lib\site-packages\pkg_resources\_vendor\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "c:\data\some_tool\server_next\backend\env\lib\site-packages\setuptools\sandbox.py", line 157, in save_modules
        yield saved
      File "c:\data\some_tool\server_next\backend\env\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
        yield
      File "c:\data\some_tool\server_next\backend\env\lib\site-packages\setuptools\sandbox.py", line 248, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "c:\data\some_tool\server_next\backend\env\lib\site-packages\setuptools\sandbox.py", line 278, in run
        return func()
      File "c:\data\some_tool\server_next\backend\env\lib\site-packages\setuptools\sandbox.py", line 246, in runner
        _execfile(setup_script, ns)
      File "c:\data\some_tool\server_next\backend\env\lib\site-packages\setuptools\sandbox.py", line 46, in _execfile
        code = compile(script, filename, 'exec')
      File "C:\Users\some_user\AppData\Local\Temp\easy_install-iw843ifh\coverage-6.0.2\setup.py", line 116
        author=f'Ned Batchelder and {num_others} others',
                                                       ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\some_user\AppData\Local\Temp\pip-build-7umvissg\flask-mongoengine\
```

It is trying to install coverage-6.0.2 and it looks like a placeholder has not been replaced properly by the time setup.py is run.I I tested it with python 3.5 and 3.6 in a virtual environment.

**Comment by nedbat** [comment]
Your stack traces are from Python 3.5, which is not supported by coverage 6.0.2.  What command are you using to install, and what version of pip do you have?

**Comment by MartyMcFlyInTheSky** [comment]
I'm using pip version 9.0.1 on a requirements.txt which has
`flask-mongoengine==0.8.2`
specified.
What python version does coverage 6.0.2 need?

**Comment by nedbat** [comment]
Pip 9.0.1 is five years old. Definitely upgrade pip.  Coverage 6.x needs Python 3.6 or greater.

**Comment by MartyMcFlyInTheSky** [comment]
Thank you! It's resolved. I switched to python 3.6 and upgraded pip and then it worked!
