### ISSUE TITLE
TypeError in sqldata.py", line 885, in <setcomp>: None > 0

### ISSUE THREAD

**Issue by terryjreedy** [coveragepy/coveragepy#1309]
I often run coverage on cpython test files in branches of main before merging.  Today I upgraded from an old version.
A. Install coverage-6.2-cp311-cp311-win_amd64.whl into 3.11.0a4.  (Thanks for 3.11 version!)
B. Copy site-packages/coverage next to my local repository.
I have run the following .bat commands for years:
```
setlocal
set py=f:\dev\3x\pcbuild\amd64\python_d.exe
set src=idlelib.%1
if "%2" EQU "" set tst=f:/dev/3x/Lib/idlelib/idle_test/test_%1.py
if "%2" NEQ "" set tst=f:/dev/3x/Lib/idlelib/idle_test/test_%2.py

%py% -m coverage run --pylib --source=%src% %tst%
%py% -m coverage report --show-missing
%py% -m coverage html
start htmlcov\3x_Lib_idlelib_%1_py.html
```
Today, with Python 3.11.0a4+ (main, Jan 23 2022, 22:42:32) [MSC v.1900 64 bit (AMD64)], all 5idlelib/idle_test/test_xyz files I tried, such as `test_run` on main branch, still run and pass, but `coverage html` (as determined by commenting out lines) results in the following:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "F:\dev\coverage\__main__.py", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "F:\dev\coverage\cmdline.py", line 881, in main
    status = CoverageScript().command_line(argv)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\dev\coverage\cmdline.py", line 627, in command_line
    total = self.coverage.report(
            ^^^^^^^^^^^^^^^^^^^^^
  File "f:\dev\3x\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\dev\coverage\control.py", line 58, in override_config
    yield
    ^^^^^
  File "F:\dev\coverage\control.py", line 934, in report
    return reporter.report(morfs, outfile=file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\dev\coverage\summary.py", line 43, in report
    for fr, analysis in get_analysis_to_report(self.coverage, morfs):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\dev\coverage\report.py", line 72, in get_analysis_to_report
    analysis = coverage._analyze(fr)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\dev\coverage\control.py", line 829, in _analyze
    return Analysis(data, self.config.precision, it, self._file_mapper)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\dev\coverage\results.py", line 24, in __init__
    executed = self.data.lines(self.filename) or []
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\dev\coverage\sqldata.py", line 885, in lines
    return list({l for l in all_lines if l > 0})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\dev\coverage\sqldata.py", line 885, in <setcomp>
    return list({l for l in all_lines if l > 0})
                                         ^^^^^
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by nedbat** [comment]
You'll need to use the latest code from GitHub if you want the latest 3.11 support.  A few things have changed since alpha-3 and 6.2.
