### ISSUE TITLE
7.0.1"pytest is failing witj `INTERNALERROR`

### ISSUE THREAD

**Issue by kloczek** [coveragepy/coveragepy#1517]
**Describe the bug**
Looks like latest pytest is failing with `INTERNALERROR`.

**To Reproduce**
I'm packaging your module as an rpm package so I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes only locally installed modules
- install .whl file in </install/prefix>
- run pytest with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

**Expected behavior**
pytest should not fail.

**Additional context**
Here is pytest output:
<details>

```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-coverage-7.0.1-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-coverage-7.0.1-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra -m 'not network'
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 268, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/tkloczko/rpmbuild/BUILD/coveragepy-7.0.1/tests/conftest.py", line 95, in pytest_sessionstart
INTERNALERROR>     assert pth_dir
INTERNALERROR> AssertionError: assert None
```
</details>

Here is list of installed modules in build env
<details>

```console
Package           Version
----------------- --------------
appdirs           1.4.4
asn1crypto        1.5.1
attrs             22.2.0
bcrypt            3.2.2
black             22.12.0
Brlapi            0.8.3
build             0.9.0
cffi              1.15.1
click             8.1.3
colorama          0.4.6
contourpy         1.0.6
cryptography      38.0.4
cssselect         1.1.0
cycler            0.11.0
distro            1.8.0
dnspython         2.2.1
exceptiongroup    1.0.0
extras            1.0.0
fixtures          4.0.0
fonttools         4.38.0
gpg               1.18.0-unknown
hypothesis        6.61.0
hypothesmith      0.2.3
iniconfig         1.1.1
kiwisolver        1.4.4
lark              1.1.5
libcomps          0.1.19
libcst            0.4.9
louis             3.24.0
lxml              4.9.1
matplotlib        3.6.2
mccabe            0.7.0
mypy-extensions   0.4.3
numpy             1.23.1
olefile           0.46
packaging         21.3
pathspec          0.10.3
pbr               5.9.0
pep517            0.13.0
Pillow            9.3.0
pip               22.3.1
platformdirs      2.6.0
pluggy            1.0.0
ply               3.11
poetry-core       1.4.0
py-cpuinfo        9.0.0
pyasn1            0.4.8
pyasn1-modules    0.2.8
pycodestyle       2.9.1
pycparser         2.21
pydocstyle        6.1.1
pyflakes          2.5.0
PyGObject         3.42.2
pylama            8.4.1
pyparsing         3.0.9
pytest            7.2.0
pytest-benchmark  4.0.0
pytest-mock       3.10.0
python-dateutil   2.8.2
PyYAML            6.0
rpm               4.17.0
scour             0.38.2
setuptools        65.6.3
six               1.16.0
snowballstemmer   2.2.0
sortedcontainers  2.4.0
testtools         2.5.0
toml              0.10.2
tomli             2.0.1
tpm2-pkcs11-tools 1.33.7
tpm2-pytss        1.1.0
typing_extensions 4.4.0
typing-inspect    0.7.1
wheel             0.38.4
```
</details>

**Comment by kloczek** [comment]
Closing.
I forgot that I've alredy have opened ticket for that https://github.com/nedbat/coveragepy/issues/1373
