### ISSUE TITLE
Getting internal Error, after receiving the value from the function

### ISSUE THREAD

**Issue by SushilG96** [coveragepy/coveragepy#1549]
Failing Intermeditaly, Pointing to INTERNALERROR, As It's expecting the value that is expected by the function, the function has been returning the value but still, getting `ValueError: need more than 0 values to unpack`.

CMD:
```
 /bin/python2.7 -m pytest test/path --cov-report=term --cov-report=html --cov-config=modules/framework/.coveragerc --cov
```
```
└──╼$ /bin/python2.7 -m coverage debug sys
-- sys -------------------------------------------------------
                        version: 5.5
                       coverage: /home/s_user/.local/lib/python2.7/site-packages/coverage/__init__.pyc
                         tracer: -none-
                        CTracer: available
           plugins.file_tracers: -none-
            plugins.configurers: -none-
      plugins.context_switchers: -none-
              configs_attempted: .coveragerc
                                 setup.cfg
                                 tox.ini
                                 pyproject.toml
                   configs_read: -none-
                    config_file: None
                config_contents: -none-
                      data_file: -none-
                         python: 2.7.5 (default, Jun 28 2022, 15:30:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
                       platform: Linux-3.10.0-1160.66.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core
                 implementation: CPython
                     executable: /bin/python2.7
                   def_encoding: ascii
                    fs_encoding: UTF-8
                            pid: 29194
                            cwd: /home/s_user/lcm-framework
                           path:
                                 /opt/rh/devtoolset-7/root/usr/lib64/python2.7/site-packages
                                 /opt/rh/devtoolset-7/root/usr/lib/python2.7/site-packages
                                 /usr/lib64/python27.zip
                                 /usr/lib64/python2.7
                                 /usr/lib64/python2.7/plat-linux2
                                 /usr/lib64/python2.7/lib-tk
                                 /usr/lib64/python2.7/lib-old
                                 /usr/lib64/python2.7/lib-dynload
                                 /home/s_user/.local/lib/python2.7/site-packages
                                 /usr/lib64/python2.7/site-packages
                                 /usr/lib/python2.7/site-packages
                    environment: PYTHONPATH = /opt/rh/devtoolset-7/root/usr/lib64/python2.7/site-packages:/opt/rh/devtoolset-7/root/usr/lib/python2.7/site-packages
                   command_line: /home/s_user/.local/lib/python2.7/site-packages/coverage/__main__.py debug sys
                sqlite3_version: 2.6.0
         sqlite3_sqlite_version: 3.7.17
             sqlite3_temp_store: 0
        sqlite3_compile_options: DISABLE_DIRSYNC
                                 ENABLE_COLUMN_METADATA
                                 ENABLE_FTS3
                                 ENABLE_RTREE
                                 ENABLE_UNLOCK_NOTIFY
                                 SECURE_DELETE
                                 TEMP_STORE=1
                                 THREADSAFE=1
```

Error:
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/s_user/.local/lib/python2.7/site-packages/_pytest/main.py", line 185, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/s_user/.local/lib/python2.7/site-packages/_pytest/main.py", line 225, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/s_user/.local/lib/python2.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/s_user/.local/lib/python2.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/s_user/.local/lib/python2.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/s_user/.local/lib/python2.7/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/home/s_user/.local/lib/python2.7/site-packages/pytest_cov/plugin.py", line 229, in pytest_runtestloop
INTERNALERROR>     self.cov_controller.finish()
INTERNALERROR>   File "/home/s_user/.local/lib/python2.7/site-packages/pytest_cov/engine.py", line 167, in finish
INTERNALERROR>     self.cov.stop()
INTERNALERROR>   File "/home/s_user/.local/lib/python2.7/site-packages/coverage/control.py", line 706, in combine
INTERNALERROR>     keep=keep,
INTERNALERROR>   File "/home/s_user/.local/lib/python2.7/site-packages/coverage/data.py", line 83, in combine_parallel_data
INTERNALERROR>     data_dir, local = os.path.split(data.base_filename())
INTERNALERROR> ValueError: need more than 0 values to unpack
```
So, I was debugging to try to print the return value of the function `data.base_filename()`, it gave the string expected but still it's failing.
value, i.e return value of the function: `'/home/s_user/lcm-framework/.coverage'`

It's very strange that am I getting this issue intermediately, 3 out of 5 times.

**Comment by nedbat** [comment]
I'm not sure what would be causing this.  Perhaps you could add some debugging output to the coverage.py code to see what `data.base_filename()` is.  You are running an old version because you are on Python 2.7, so I'm not sure how else to fix this.

**Comment by nedbat** [comment]
If you get more information about what's going wrong, feel free to reopen this.
