### ISSUE TITLE
Not able to install coverage 7.2 on Python 3.8, it shows "AttributeError: module 'collections.abc' has no attribute 'Seq'"

### ISSUE THREAD

**Issue by lgt1001** [coveragepy/coveragepy#1562]
**Describe the bug**
Not able to install coverage 7.2 on Python 3.8

**To Reproduce**
It shows error.
```
Traceback (most recent call last):
  File "C:\hello\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in _main
    status = self.run(options, args)
  File "C:\hello\venv\lib\site-packages\pip\_internal\cli\req_command.py", line 204, in wrapper
    return func(self, options, args)
  File "C:\hello\venv\lib\site-packages\pip\_internal\commands\install.py", line 303, in run
    resolver = self.make_resolver(
  File "C:\hello\venv\lib\site-packages\pip\_internal\cli\req_command.py", line 311, in make_resolver
    import pip._internal.resolution.resolvelib.resolver
  File "C:\hello\venv\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 22, in <module>
    from pip._internal.resolution.resolvelib.provider import PipProvider
  File "C:\hello\venv\lib\site-packages\pip\_internal\resolution\resolvelib\provider.py", line 6, in <module>
    from .factory import Factory
  File "C:\hello\venv\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 62, in <module>
    from .found_candidates import FoundCandidates, IndexCandidateInfo
  File "C:\hello\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 92, in <module>
    class FoundCandidates(collections_abc.Seq):
AttributeError: module 'collections.abc' has no attribute 'Seq'
```

**Comment by nedbat** [comment]
I am not seeing that problem.  Perhaps your version of pip needs to be updated?  What version do you have?
