### ISSUE TITLE
Cannot submit coverage since update to 7.2.4

### ISSUE THREAD

**Issue by elParaguayo** [coveragepy/coveragepy#1615]
**Describe the bug**
We have been using `coverage` in our Github Actions CI test suite. The latest run of this suite has failed with the following error:

```
Submitting coverage to coveralls.io...
Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
resubmitting with id None
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/coveralls/api.py", line 290, in submit_report
    response.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/coveralls/cli.py", line 95, in main
    result = coverallz.wear()
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/coveralls/api.py", line 257, in wear
    return self.submit_report(json_string)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/coveralls/api.py", line 293, in submit_report
    raise CoverallsException(
coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
```

The error happens when we try to upload the coverage report with `coveralls`. Given that there's no update to coveralls and `coverage` has updated recently. I believe the error is caused by updates to this package.

**To Reproduce**
How can we reproduce the problem?  Please *be specific*. Don't link to a failing CI job. Answer the questions below:
1. What version of Python are you using?
We run python 3.9/10/11 in our suite. I've seen failures on both 3.10 and 3.11 (the 3.9 tests were cancelled due to these failures)

1. What version of coverage.py shows the problem? The output of `coverage debug sys` is helpful.
This is 7.2.4

1. What versions of what packages do you have installed? The output of `pip freeze` is helpful.
1. What code shows the problem?  Give us a specific commit of a specific repo that we can check out. If you've already worked around the problem, please provide a commit before that fix.
Here's the failure: https://github.com/qtile/qtile/actions/runs/4821766697/jobs/8613951134

The relevant lines in our test suite are:
```
coverage run -m pytest --backend=x11 --backend=wayland {posargs}
coverage combine -q
# Include a text summary in the build log
coverage report -m
# Create an xml summary to be submitted to coveralls.io
coverage xml
```
The code is then uploaded via `coveralls --service=github`. 

1. What commands did you run?

**Expected behavior**
I expect the coverage to upload successfully.

**Additional context**
Apologies if this is caused by some stupid error on my part but it's been working well for a long time and stopped after the 7.2.4 update.

I haven't yet confirmed that 7.2.4 is the cause by pinning `coverage` to an earlier version but I will do that separately and post a link here.

**Comment by elParaguayo** [comment]
Needs further investigating. Both 7.2.4 (https://github.com/qtile/qtile/pull/4244) and 7.2.3 (https://github.com/qtile/qtile/pull/4245) are failing so looks like `coverage` isn't the issue!

**Comment by elParaguayo** [comment]
Going to close this as I think the timing of 7.2.4 may just be coincidental.
