### ISSUE TITLE
coverage-7.2.7 is failing on Python 3.12.0-alpha (1 to 7) (but is working on 3.12.0-beta)

### ISSUE THREAD

**Issue by SylvainDe** [coveragepy/coveragepy#1634]
**Describe the bug**

Trying to use coverage on a personal project, I started to have a new issue this morning when it used coverage-7.2.7 for the first time:

```
  coverage run -m unittest discover --start-directory=didyoumean --pattern=*.py

  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.12.0-alpha.1/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.0-alpha.1/x64/lib
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.0-alpha.1/x64/bin/coverage", line 8, in <module>
  File "/opt/hostedtoolcache/Python/3.12.0-alpha.1/x64/lib/python3.12/site-packages/coverage/cmdline.py", line 973, in main
  File "/opt/hostedtoolcache/Python/3.12.0-alpha.1/x64/lib/python3.12/site-packages/coverage/cmdline.py", line 684, in command_line
  File "/opt/hostedtoolcache/Python/3.12.0-alpha.1/x64/lib/python3.12/site-packages/coverage/cmdline.py", line 858, in do_run
  File "/opt/hostedtoolcache/Python/3.12.0-alpha.1/x64/lib/python3.12/site-packages/coverage/control.py", line 638, in start
  File "/opt/hostedtoolcache/Python/3.12.0-alpha.1/x64/lib/python3.12/site-packages/coverage/collector.py", line 364, in start
  File "/opt/hostedtoolcache/Python/3.12.0-alpha.1/x64/lib/python3.12/threading.py", line 82, in settrace
  File "/opt/hostedtoolcache/Python/3.12.0-alpha.1/x64/lib/python3.12/site-packages/coverage/control.py", line 384, in _should_trace
  File "/opt/hostedtoolcache/Python/3.12.0-alpha.1/x64/lib/python3.12/site-packages/coverage/inorout.py", line 316, in should_trace
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.0-alpha.1/x64/lib/python3.12/threading.py", line 1545, in _shutdown
  File "/opt/hostedtoolcache/Python/3.12.0-alpha.1/x64/lib/python3.12/site-packages/coverage/control.py", line 384, in _should_trace
  File "/opt/hostedtoolcache/Python/3.12.0-alpha.1/x64/lib/python3.12/site-packages/coverage/inorout.py", line 316, in should_trace
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
Exception ignored in atexit callback: <bound method Coverage._atexit of <coverage.control.Coverage object at 0x7f2142f35190>>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.0-alpha.1/x64/lib/python3.12/site-packages/coverage/control.py", line 652, in _atexit
  File "/opt/hostedtoolcache/Python/3.12.0-alpha.1/x64/lib/python3.12/site-packages/coverage/control.py", line 384, in _should_trace
  File "/opt/hostedtoolcache/Python/3.12.0-alpha.1/x64/lib/python3.12/site-packages/coverage/inorout.py", line 316, in should_trace
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
Error: Process completed with exit code 1.
```

**To Reproduce**
How can we reproduce the problem?
1. What version of Python are you using?

It is very peculiar that:

- it does work fine on Python 3.11 (0 to 3)
- it does NOT work on Python 3.12.0-alpha (1 to 7)
- it does work fine on Python 3.12.0-beta0

1. What version of coverage.py shows the problem? The output of `coverage debug sys` is helpful.

I started to have the problem with coverage-7.2.7 . Before that, coverage-7.2.6 was used with no problem whatsoever.

1. What versions of what packages do you have installed?

No other dependency

1. What code shows the problem?  Give us a specific commit of a specific repo that we can check out. If you've already worked around the problem, please provide a commit before that fix.

The branch https://github.com/SylvainDe/DidYouMean-Python/tree/issue62-coverage727-startswith goes the issue on a minimalist piece of code: here is the test https://github.com/SylvainDe/DidYouMean-Python/blob/issue62-coverage727-startswith/didyoumean/fake_tests.py 

1. What commands should we run to reproduce the problem? *Be specific*. Include everything, even `git clone`, `pip install`, and so on. Explain like we're five!

From the branch mentionned above, here is the github workflow code: https://github.com/SylvainDe/DidYouMean-Python/blob/issue62-coverage727-startswith/.github/workflows/my_github_action.yml which gave https://github.com/SylvainDe/DidYouMean-Python/actions/runs/5125470423 .

**Expected behavior**

No error and output:

```
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
```

**Additional context**

I do not have much context: I find this issue very surprising and did not find any explanation in the Coverage changelog or the CPython changelog.

The issue created on my project is: https://github.com/SylvainDe/DidYouMean-Python/issues/62 .

I understand that this issue is very low priority (or could even be considered as invalid) so I'm not expecting a fix for it but I thought that it may be interested to you (and I'd be happy to learn about the explanation).

**Comment by nedbat** [comment]
The difference in 7.2.7 is that it ships wheels for 3.12, but 7.2.6 did not.  For the earlier version, either you were building the C extension yourself at install time, or you were using the Python tracer instead of the C tracer.

Can you run 7.2.6 on Python 3.12, and show the output of `coverage debug sys`?

**Comment by nedbat** [comment]
I think the behavior you are seeing is caused by running C code compiled for 3.11.0b1 on an alpha build.

**Comment by SylvainDe** [comment]
Thanks, this looks like a possible explanation!

For the record, I've launched a CI jobs to get the information you are interested in: https://github.com/SylvainDe/DidYouMean-Python/actions/runs/5126428118 .

We have on alpha:


```

Python 3.12.0a7 (main, Apr  5 2023, 12:47:07) [GCC 9.4.0]
sys.version_info(major=3, minor=12, micro=0, releaselevel='alpha', serial=7)
('CPython', '', '')
pip 23.1.2 from /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64/lib/python3.12/site-packages/pip (python 3.12)




coverage debug sys || true
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64/lib
-- sys -------------------------------------------------------
               coverage_version: 7.2.6
                coverage_module: /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64/lib/python3.12/site-packages/coverage/__init__.py
                         tracer: -none-
                        CTracer: available
           plugins.file_tracers: -none-
            plugins.configurers: -none-
      plugins.context_switchers: -none-
              configs_attempted: .coveragerc
                   configs_read: /home/runner/work/DidYouMean-Python/DidYouMean-Python/.coveragerc
                    config_file: /home/runner/work/DidYouMean-Python/DidYouMean-Python/.coveragerc
                config_contents: b'[run]\nsource = didyoumean\n'
                      data_file: -none-
                         python: 3.12.0a7 (main, Apr  5 2023, 12:47:07) [GCC 9.4.0]
                       platform: Linux-5.15.0-1037-azure-x86_64-with-glibc2.31
                 implementation: CPython
                     executable: /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64/bin/python
                   def_encoding: utf-8
                    fs_encoding: utf-8
                            pid: 1799
                            cwd: /home/runner/work/DidYouMean-Python/DidYouMean-Python
                           path: /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64/bin
                                 /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64/lib/python312.zip
                                 /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64/lib/python3.12
                                 /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64/lib/python3.12/lib-dynload
                                 /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64/lib/python3.12/site-packages
                    environment: HOME = /home/runner
                   command_line: /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64/bin/coverage debug sys
         sqlite3_sqlite_version: 3.31.1
             sqlite3_temp_store: 0
        sqlite3_compile_options: COMPILER=gcc-9.4.0, ENABLE_COLUMN_METADATA, ENABLE_DBSTAT_VTAB,
                                 ENABLE_FTS3, ENABLE_FTS3_PARENTHESIS, ENABLE_FTS3_TOKENIZER, ENABLE_FTS4,
                                 ENABLE_FTS5, ENABLE_JSON1, ENABLE_LOAD_EXTENSION, ENABLE_PREUPDATE_HOOK,
                                 ENABLE_RTREE, ENABLE_SESSION, ENABLE_STMTVTAB, ENABLE_UNLOCK_NOTIFY,
                                 ENABLE_UPDATE_DELETE_LIMIT, HAVE_ISNAN, LIKE_DOESNT_MATCH_BLOBS,
                                 MAX_SCHEMA_RETRY=25, MAX_VARIABLE_NUMBER=250000, OMIT_LOOKASIDE,
                                 SECURE_DELETE, SOUNDEX, TEMP_STORE=1, THREADSAFE=1, USE_URI
                                 
(which works)



  coverage debug sys || true
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64/lib
-- sys -------------------------------------------------------
               coverage_version: 7.2.7
                coverage_module: /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64/lib/python3.12/site-packages/coverage/__init__.py
                         tracer: -none-
                        CTracer: available
           plugins.file_tracers: -none-
            plugins.configurers: -none-
      plugins.context_switchers: -none-
              configs_attempted: .coveragerc
                   configs_read: /home/runner/work/DidYouMean-Python/DidYouMean-Python/.coveragerc
                    config_file: /home/runner/work/DidYouMean-Python/DidYouMean-Python/.coveragerc
                config_contents: b'[run]\nsource = didyoumean\n'
                      data_file: -none-
                         python: 3.12.0a7 (main, Apr  5 2023, 12:47:07) [GCC 9.4.0]
                       platform: Linux-5.15.0-1037-azure-x86_64-with-glibc2.31
                 implementation: CPython
                     executable: /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64/bin/python
                   def_encoding: utf-8
                    fs_encoding: utf-8
                            pid: 1821
                            cwd: /home/runner/work/DidYouMean-Python/DidYouMean-Python
                           path: /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64/bin
                                 /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64/lib/python312.zip
                                 /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64/lib/python3.12
                                 /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64/lib/python3.12/lib-dynload
                                 /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64/lib/python3.12/site-packages
                    environment: HOME = /home/runner
                   command_line: /opt/hostedtoolcache/Python/3.12.0-alpha.7/x64/bin/coverage debug sys
         sqlite3_sqlite_version: 3.31.1
             sqlite3_temp_store: 0
        sqlite3_compile_options: COMPILER=gcc-9.4.0, ENABLE_COLUMN_METADATA, ENABLE_DBSTAT_VTAB,
                                 ENABLE_FTS3, ENABLE_FTS3_PARENTHESIS, ENABLE_FTS3_TOKENIZER, ENABLE_FTS4,
                                 ENABLE_FTS5, ENABLE_JSON1, ENABLE_LOAD_EXTENSION, ENABLE_PREUPDATE_HOOK,
                                 ENABLE_RTREE, ENABLE_SESSION, ENABLE_STMTVTAB, ENABLE_UNLOCK_NOTIFY,
                                 ENABLE_UPDATE_DELETE_LIMIT, HAVE_ISNAN, LIKE_DOESNT_MATCH_BLOBS,
                                 MAX_SCHEMA_RETRY=25, MAX_VARIABLE_NUMBER=250000, OMIT_LOOKASIDE,
                                 SECURE_DELETE, SOUNDEX, TEMP_STORE=1, THREADSAFE=1, USE_URI
                                 
(which does not work)
```

and on beta:

```

Python 3.12.0b1 (main, May 25 2023, 06:36:39) [GCC 9.4.0]
sys.version_info(major=3, minor=12, micro=0, releaselevel='beta', serial=1)
('CPython', '', '')
pip 23.1.2 from /opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/site-packages/pip (python 3.12)




coverage debug sys || true
  coverage debug sys || true
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.12.0-beta.1/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.0-beta.1/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.0-beta.1/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.0-beta.1/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib
-- sys -------------------------------------------------------
               coverage_version: 7.2.6
                coverage_module: /opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/site-packages/coverage/__init__.py
                         tracer: -none-
                        CTracer: available
           plugins.file_tracers: -none-
            plugins.configurers: -none-
      plugins.context_switchers: -none-
              configs_attempted: .coveragerc
                   configs_read: /home/runner/work/DidYouMean-Python/DidYouMean-Python/.coveragerc
                    config_file: /home/runner/work/DidYouMean-Python/DidYouMean-Python/.coveragerc
                config_contents: b'[run]\nsource = didyoumean\n'
                      data_file: -none-
                         python: 3.12.0b1 (main, May 25 2023, 06:36:39) [GCC 9.4.0]
                       platform: Linux-5.15.0-1037-azure-x86_64-with-glibc2.31
                 implementation: CPython
                     executable: /opt/hostedtoolcache/Python/3.12.0-beta.1/x64/bin/python
                   def_encoding: utf-8
                    fs_encoding: utf-8
                            pid: 1789
                            cwd: /home/runner/work/DidYouMean-Python/DidYouMean-Python
                           path: /opt/hostedtoolcache/Python/3.12.0-beta.1/x64/bin
                                 /opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python312.zip
                                 /opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12
                                 /opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/lib-dynload
                                 /opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/site-packages
                    environment: HOME = /home/runner
                   command_line: /opt/hostedtoolcache/Python/3.12.0-beta.1/x64/bin/coverage debug sys
         sqlite3_sqlite_version: 3.31.1
             sqlite3_temp_store: 0
        sqlite3_compile_options: COMPILER=gcc-9.4.0, ENABLE_COLUMN_METADATA, ENABLE_DBSTAT_VTAB,
                                 ENABLE_FTS3, ENABLE_FTS3_PARENTHESIS, ENABLE_FTS3_TOKENIZER, ENABLE_FTS4,
                                 ENABLE_FTS5, ENABLE_JSON1, ENABLE_LOAD_EXTENSION, ENABLE_PREUPDATE_HOOK,
                                 ENABLE_RTREE, ENABLE_SESSION, ENABLE_STMTVTAB, ENABLE_UNLOCK_NOTIFY,
                                 ENABLE_UPDATE_DELETE_LIMIT, HAVE_ISNAN, LIKE_DOESNT_MATCH_BLOBS,
                                 MAX_SCHEMA_RETRY=25, MAX_VARIABLE_NUMBER=250000, OMIT_LOOKASIDE,
                                 SECURE_DELETE, SOUNDEX, TEMP_STORE=1, THREADSAFE=1, USE_URI
                                 
(which works)                  
                                 
  coverage debug sys || true
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.12.0-beta.1/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.0-beta.1/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.0-beta.1/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.0-beta.1/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib
-- sys -------------------------------------------------------
               coverage_version: 7.2.7
                coverage_module: /opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/site-packages/coverage/__init__.py
                         tracer: -none-
                        CTracer: available
           plugins.file_tracers: -none-
            plugins.configurers: -none-
      plugins.context_switchers: -none-
              configs_attempted: .coveragerc
                   configs_read: /home/runner/work/DidYouMean-Python/DidYouMean-Python/.coveragerc
                    config_file: /home/runner/work/DidYouMean-Python/DidYouMean-Python/.coveragerc
                config_contents: b'[run]\nsource = didyoumean\n'
                      data_file: -none-
                         python: 3.12.0b1 (main, May 25 2023, 06:36:39) [GCC 9.4.0]
                       platform: Linux-5.15.0-1037-azure-x86_64-with-glibc2.31
                 implementation: CPython
                     executable: /opt/hostedtoolcache/Python/3.12.0-beta.1/x64/bin/python
                   def_encoding: utf-8
                    fs_encoding: utf-8
                            pid: 1811
                            cwd: /home/runner/work/DidYouMean-Python/DidYouMean-Python
                           path: /opt/hostedtoolcache/Python/3.12.0-beta.1/x64/bin
                                 /opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python312.zip
                                 /opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12
                                 /opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/lib-dynload
                                 /opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/site-packages
                    environment: HOME = /home/runner
                   command_line: /opt/hostedtoolcache/Python/3.12.0-beta.1/x64/bin/coverage debug sys
         sqlite3_sqlite_version: 3.31.1
             sqlite3_temp_store: 0
        sqlite3_compile_options: COMPILER=gcc-9.4.0, ENABLE_COLUMN_METADATA, ENABLE_DBSTAT_VTAB,
                                 ENABLE_FTS3, ENABLE_FTS3_PARENTHESIS, ENABLE_FTS3_TOKENIZER, ENABLE_FTS4,
                                 ENABLE_FTS5, ENABLE_JSON1, ENABLE_LOAD_EXTENSION, ENABLE_PREUPDATE_HOOK,
                                 ENABLE_RTREE, ENABLE_SESSION, ENABLE_STMTVTAB, ENABLE_UNLOCK_NOTIFY,
                                 ENABLE_UPDATE_DELETE_LIMIT, HAVE_ISNAN, LIKE_DOESNT_MATCH_BLOBS,
                                 MAX_SCHEMA_RETRY=25, MAX_VARIABLE_NUMBER=250000, OMIT_LOOKASIDE,
                                 SECURE_DELETE, SOUNDEX, TEMP_STORE=1, THREADSAFE=1, USE_URI
                                 
(which also works)
```

**Comment by nedbat** [comment]
I can confirm that the 7.2.7 wheels for 3.12.0b1 will cause the problem you show for 3.12 alpha builds.  I could add a detailed version support statement to the docs.

**Comment by SylvainDe** [comment]
That could be an idea. Also, maybe my use case is not that interesting to start with as not many people care about running coverage on alpha versions when beta versions are already released....

Thanks again for your investigation (and obviously, feel free to close the ticket when you've done whatever you want to do)

**Comment by nedbat** [comment]
I'm curious: why are you still running the alphas, now that we have beta 1?

**Comment by SylvainDe** [comment]
The short answer is that I should probably not bother much.

The long answer is that my project is not maintained anymore except for the fact that it checks a few edge cases of CPython (and Pypy) that are not that well tested. Hence, just in case it can be useful, I make sure that I try it on all versions that I can put my hands on as it makes investigation easier when you can tell quickly that things got broken between Python x.y.z1 and Python x.y.z2.

As a reference: https://github.com/SylvainDe/DidYouMean-Python/blob/master/RelatedPythonIssues.md (at least for 2 of theses issues, I've bothered you with the (wrong) assumption that it was a Coverage bug).
