### ISSUE TITLE
coverage seems to cause coroutines to skip over exeption handlers on 3.12

### ISSUE THREAD

**Issue by graingert** [coveragepy/coveragepy#1635]
https://github.com/urllib3/urllib3/issues/3049#issuecomment-1570452951

**Describe the bug**
when running on 3.12b1 and coverage 7.2.7 (with C extension) coverage seems to cause coroutines to skip over exeption handlers

**To Reproduce**
How can we reproduce the problem?  Please *be specific*. Don't link to a failing CI job. Answer the questions below:
1. What version of Python are you using? 3.12b1
1. What version of coverage.py shows the problem? The output of `coverage debug sys` is helpful. 7.2.7
1. What versions of what packages do you have installed? The output of `pip freeze` is helpful.
1. What code shows the problem?  Give us a specific commit of a specific repo that we can check out. If you've already worked around the problem, please provide a commit before that fix. https://github.com/urllib3/urllib3/issues/3049#issuecomment-1570452951

input:
```python
import asyncio

async def inner():
    loop = asyncio.get_running_loop()
    fut = loop.create_future()
    loop.call_later(0.1, fut.set_exception, Exception())
    try:
        await fut
    except Exception:
        print("good")

async def main():
    await inner()

asyncio.run(main())
```

**Expected behavior**
```
 graingert@conscientious  ~/projects/urllib3   py3-12-debug ± ./.nox/test-3-12/bin/coverage run -m demo
Traceback (most recent call last):
  File "/home/graingert/projects/urllib3/demo.py", line 15, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/graingert/projects/urllib3/demo.py", line 13, in main
    await inner()
Exception
 ✘  graingert@conscientious  ~/projects/urllib3   py3-12-debug ± vim demo.py 
 graingert@conscientious  ~/projects/urllib3   py3-12-debug ± ./.nox/test-3-12/bin/python -m demo
good
```

**Additional context**

**Comment by graingert** [comment]
eliminating asyncio:

```python
import types

@types.coroutine
def _async_yield(v):
    return (yield v)

async def inner():
    try:
        await _async_yield(None)
    except Exception:
        print("good")
    return "good2"

async def main():
    return await inner()

def run(coro):
    coro.send(None)
    try:
        coro.throw(Exception)
    except StopIteration as e:
        print(e.value)


run(main())
```

```
 graingert@conscientious  ~/projects/urllib3   py3-12-debug ± ./.nox/test-3-12/bin/coverage run -m demo
Traceback (most recent call last):
  File "/home/graingert/projects/urllib3/demo.py", line 25, in <module>
    run(main())
  File "/home/graingert/projects/urllib3/demo.py", line 20, in run
    coro.throw(Exception)
  File "/home/graingert/projects/urllib3/demo.py", line 15, in main
    return await inner()
           ^^^^^^^^^^^^^
Exception
 ✘  graingert@conscientious  ~/projects/urllib3   py3-12-debug ± ./.nox/test-3-12/bin/python -m demo      
good
good2
```

**Comment by graingert** [comment]
same with a plain generator:

```python
def inner():
    try:
        yield None
    except Exception:
        print("good")
    return "good2"

def main():
    return (yield from inner())

def run(coro):
    coro.send(None)
    try:
        coro.throw(Exception)
    except StopIteration as e:
        print(e.value)


run(main())
```

```
 graingert@conscientious  ~/projects/urllib3   py3-12-debug ± ./.nox/test-3-12/bin/coverage run -m demo
Traceback (most recent call last):
  File "/home/graingert/projects/urllib3/demo.py", line 19, in <module>
    run(main())
  File "/home/graingert/projects/urllib3/demo.py", line 14, in run
    coro.throw(Exception)
  File "/home/graingert/projects/urllib3/demo.py", line 9, in main
    return (yield from inner())
            ^^^^^^^^^^^^^^^^^^
Exception
 ✘  graingert@conscientious  ~/projects/urllib3   py3-12-debug ± ./.nox/test-3-12/bin/python -m demo      
good
good2
```

**Comment by sethmlarson** [comment]
I'm also able to reproduce this on Ubuntu w/ Python 3.12.0-beta1:

```bash
(venv) $ python --version
Python 3.12.0b1

(venv) $ python -m pip freeze
coverage==7.2.7

(venv) $ coverage run -m demo
Traceback (most recent call last):
  File "/tmp/demo.py", line 19, in <module>
    run(main())
  File "/tmp/demo.py", line 14, in run
    coro.throw(Exception)
  File "/tmp/demo.py", line 9, in main
    return (yield from inner())
            ^^^^^^^^^^^^^^^^^^
Exception

(venv) $ python -m demo
good
good2
```

**Comment by graingert** [comment]
same issue using a manually written Inner generator:

```python
class Inner:
    def send(self, v):
        return None

    def __iter__(self):
        return self

    def __next__(self):
        return self.send(None)

    def throw(self, *exc_info):
        raise StopIteration("good")


def main():
    return (yield from Inner())

def run(coro):
    coro.send(None)
    try:
        coro.throw(Exception)
    except StopIteration as e:
        print(e.value)


run(main())
```

**Comment by graingert** [comment]
eliminating coverage:

```python
./.nox/test-3-12/bin/python -m trace --count -C . demo.py
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.12/trace.py", line 741, in <module>
    main()
  File "/usr/lib/python3.12/trace.py", line 729, in main
    t.runctx(code, globs, globs)
  File "/usr/lib/python3.12/trace.py", line 451, in runctx
    exec(cmd, globals, locals)
  File "demo.py", line 26, in <module>
    run(main())
  File "demo.py", line 21, in run
    coro.throw(Exception)
  File "demo.py", line 16, in main
    return (yield from Inner())
            ^^^^^^^^^^^^^^^^^^
Exception
```

**Comment by pquentin** [comment]
This turned out to be a CPython issue, so I think this can be safely closed.

**Comment by graingert** [comment]
Closed, there's a CPython fix proposed already!

https://github.com/python/cpython/issues/105162
