### ISSUE TITLE
Missing coverage when using the "redis" library

### ISSUE THREAD

**Issue by krieghan** [coveragepy/coveragepy#1671]
**Describe the bug**
When using asyncio with redis.asyncio (redispy), some lines that are definitely hit remain mysteriously uncovered, even when using a combination of different concurrency settings

**To Reproduce**
1. Python version 3.11.4, with coverage 7.3.0 and redis 5.0.0 (OS is Ubuntu 22.04)
2. My .coveragerc file:

```
[run]
source = .
parallel = True
concurrency = 
    thread
    gevent
    multiprocessing
```

(I've tried various combinations of concurrency, but I most often leave it blank.  I suspect it's not even appropriate for my application, though I'm not certain)

My minimal example (coverage_test.py):

```python
import asyncio

import redis.asyncio as redis


async def main():
    client = redis.Redis()
    result = await client.get('key')
    print('running main')

if __name__ == '__main__':
    asyncio.run(main())
    print('finished main')
```

I issue the coverage command with a bash script (coverage.sh) as follows:

```
coverage erase
coverage run coverage_test.py
coverage combine
coverage html
xdg-open htmlcov/index.html
```

The output of the script is:

```
running main
finished main
```

And the coverage of the file looks like this:

![image](https://github.com/nedbat/coveragepy/assets/792633/0ccac2e0-d2af-4007-bbe9-75d36866f7d4)

I would expect the last print statement (which is executed, according to the output) to be marked green.  I see there are some similar issues (most notably https://github.com/nedbat/coveragepy/issues/1082 and https://github.com/nedbat/coveragepy/issues/1598), but as I mentioned I haven't found a concurrency setting that mitigates this.

**Comment by nedbat** [comment]
Is there a way to reproduce this without running a Redis instance?  I get a ConnectionError.

**Comment by krieghan** [comment]
Oh wow, that's a solid point.  I don't know of a way around it at the moment, but I can look into it.  Thanks for the response!

**Comment by krieghan** [comment]
I've tried for a bit to reproduce this issue with asyncio streams (which, drilling down, seems to be where the issue comes up).  I haven't been able to do it with just the naive echo client/server that python's documentation lays out.  There's something here happening that seems specific to redis-py, and I don't know how to reproduce the issue without a redis instance running :/.  I've left an inquiry on their project (basically the same information as here, but with a longer example included, as well) - I'm hoping they have some insights: https://github.com/redis/redis-py/issues/2912

**Comment by krieghan** [comment]
I saw that python released a new version for python 3.11.5.  I've tried everything again with this new version.  I still see the same behavior in coverage, but I am now seeing an additional traceback from redis as the script closes.  I thought it might be related to this line of missing coverage.  I'm including it here:

Exception ignored in: <function StreamWriter.__del__ at 0x7fcd228adb20>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 396, in __del__
    self.close()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 344, in close
    return self._transport.close()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 860, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 761, in call_soon
    self._check_closed()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by aw-was-here** [comment]
> Is there a way to reproduce this without running a Redis instance? I get a ConnectionError.

I'm seeing it using fakeredis, which is what I use to test redis code.

**Comment by nedbat** [comment]
> I'm seeing it using fakeredis, which is what I use to test redis code.

Any chance you can give us a way to reproduce it?

**Comment by aw-was-here** [comment]
> > I'm seeing it using fakeredis, which is what I use to test redis code.
> 
> Any chance you can give us a way to reproduce it?

This repo was setup in a hurry so things in `pyproject.toml` aren't correct, but it should be good enough to demonstrate: 

 https://github.com/aw-was-here/redis-cov-test

<img width="612" alt="Screen Shot 2023-12-07 at 11 05 02 PM" src="https://github.com/nedbat/coveragepy/assets/7633626/a4b0d388-c4bd-4e85-9c23-c7a272db68c7">

**Comment by nedbat** [comment]
I tried running the sample repo with coverage 7.10.4, and it covered all of the write() method, though none of before_and_after_test in the test file was run, so maybe something is wrong?  There were a number of warnings:
```
tests/test_redis.py:12
  /System/Volumes/Data/src/bugs/bug1671/redis-cov-test/tests/test_redis.py:12: PytestRemovedIn9Warning: Marks applied to fixtures have no effect
  See docs: https://docs.pytest.org/en/stable/deprecations.html#applying-a-mark-to-a-fixture-function
    @pytest.mark.asyncio

tests/test_redis.py::test_redis
  /System/Volumes/Data/src/bugs/bug1671/redis-cov-test/.venv/lib/python3.11/site-packages/_pytest/fixtures.py:1181: PytestRemovedIn9Warning: 'test_redis' requested an async fixture 'before_and_after_test' with autouse=True, with no plugin or hook that handled it. This is usually an error, as pytest does not natively support it. This will turn into an error in pytest 9.
  See: https://docs.pytest.org/en/stable/deprecations.html#sync-test-depending-on-async-fixture
    warnings.warn(

tests/test_redis.py::test_redis
  /System/Volumes/Data/src/bugs/bug1671/redis-cov-test/.venv/lib/python3.11/site-packages/pytest_asyncio/plugin.py:598: PytestDeprecationWarning: asyncio test 'test_redis' requested async @pytest.fixture 'before_and_after_test' in strict mode. You might want to use @pytest_asyncio.fixture or switch to auto mode. This will become an error in future versions of flake8-asyncio.
    warnings.warn(

tests/test_redis.py::test_redis
  /System/Volumes/Data/src/bugs/bug1671/redis-cov-test/app.py:8: DeprecationWarning: Call to deprecated close. (Use aclose() instead) -- Deprecated since version 5.0.1.
    await redis_client.close(close_connection_pool=False)

tests/test_redis.py::test_redis
  /System/Volumes/Data/src/bugs/bug1671/redis-cov-test/tests/test_redis.py:30: DeprecationWarning: Call to deprecated close. (Use aclose() instead) -- Deprecated since version 5.0.1.
    await redis_client.close()
```
I haven't written tests for async code, so I'm not sure how to bring this up to speed.
