### ISSUE TITLE
Intermittent failures of test.test_oddball:ThreadingTest on PyPy 1.8

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#187]
*Originally reported by* **Marc Abramowitz (Bitbucket: [msabramo](https://bitbucket.org/msabramo), GitHub: [msabramo](https://github.com/msabramo))**

----------------------------------------

This is in an Ubuntu 11 vm:

    
    marca@ubuntu:~/dev/git-repos/coveragepy$ while true; do PATH=$PATH:~/src/pypy-1.8/bin .tox/pypy_py/bin/nosetests test.test_oddball:ThreadingTest; sleep 1; done
    F.
    ======================================================================
    FAIL: test_thread_run (test.test_oddball.ThreadingTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/marca/dev/git-repos/coveragepy/test/test_oddball.py", line 50, in test_thread_run
        [1,3,4,5,6,7,9,10,12,13,14], "")
      File "/home/marca/dev/git-repos/coveragepy/test/coveragetest.py", line 328, in check_coverage
        self.assertEqual(analysis.missing_formatted(), missing)
    AssertionError: '14' != ''
    
    ----------------------------------------------------------------------
    Ran 2 tests in 0.378s
    
    FAILED (failures=1)
    ..
    ----------------------------------------------------------------------
    Ran 2 tests in 0.521s
    
    OK
    ..
    ----------------------------------------------------------------------
    Ran 2 tests in 0.708s
    
    OK
    ..
    ----------------------------------------------------------------------
    Ran 2 tests in 0.711s
    
    OK
    ..
    ----------------------------------------------------------------------
    Ran 2 tests in 0.576s
    
    OK
    ..
    ----------------------------------------------------------------------
    Ran 2 tests in 0.623s
    
    OK
    ..
    ----------------------------------------------------------------------
    Ran 2 tests in 0.395s
    
    OK
    ..
    ----------------------------------------------------------------------
    Ran 2 tests in 0.411s
    
    OK
    ..
    ----------------------------------------------------------------------
    Ran 2 tests in 0.413s
    
    OK
    ..
    ----------------------------------------------------------------------
    Ran 2 tests in 0.433s
    
    OK
    ..
    ----------------------------------------------------------------------
    Ran 2 tests in 0.668s
    
    OK
    ..
    ----------------------------------------------------------------------
    Ran 2 tests in 0.703s
    
    OK
    ..
    ----------------------------------------------------------------------
    Ran 2 tests in 0.385s
    
    OK
    ..
    ----------------------------------------------------------------------
    Ran 2 tests in 0.491s
    
    OK
    ..
    ----------------------------------------------------------------------
    Ran 2 tests in 0.628s
    
    OK
    .F
    ======================================================================
    FAIL: test_threading (test.test_oddball.ThreadingTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/marca/dev/git-repos/coveragepy/test/test_oddball.py", line 31, in test_threading
        [1,3,4,6,7,9,10,12,13,14,15], "10")
      File "/home/marca/dev/git-repos/coveragepy/test/coveragetest.py", line 328, in check_coverage
        self.assertEqual(analysis.missing_formatted(), missing)
    AssertionError: '4, 10, 14-15' != '10'
    
    ----------------------------------------------------------------------
    Ran 2 tests in 0.746s
    
    FAILED (failures=1)
    

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/187

**Comment by nedbat** [comment]
*Original comment by* **Marc Abramowitz (Bitbucket: [msabramo](https://bitbucket.org/msabramo), GitHub: [msabramo](https://github.com/msabramo))**

----------------------------------------

This happens quite rarely on my Ubuntu 11 vm (though it seems quite reliably reproduceable on Travis CI):

    
    marca@ubuntu:~/dev/git-repos/coveragepy$ grep -c '^OK' test.out ; grep -c '^FAILED' test.out
    718
    35
    marca@ubuntu:~/dev/git-repos/coveragepy$ python -c 'print(round(100 * 35.0 / (718.0 + 35.0), 2))'
    4.65

**Comment by nedbat** [comment]
I haven't seen this failure in a long time.
