### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'branch'

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#213]
*Originally reported by* **Anonymous**

----------------------------------------

```
/usr/lib/python2.6/site-packages/tw/core/view.py:223: DeprecationWarning: object.__new__() takes no parameters
  obj = object.__new__(cls, *args, **kw)
Traceback (most recent call last):
  File "/usr/bin/nosetests", line 9, in <module>
    load_entry_point('nose==1.2.1', 'console_scripts', 'nosetests')()
  File "/usr/lib/python2.6/site-packages/nose/core.py", line 118, in __init__
    **extra_args)
  File "/usr/lib64/python2.6/unittest.py", line 815, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.6/site-packages/nose/core.py", line 135, in parseArgs
    self.config.configure(argv, doc=self.usage())
  File "/usr/lib/python2.6/site-packages/nose/config.py", line 338, in configure
    self.plugins.configure(options, self)
  File "/usr/lib/python2.6/site-packages/nose/plugins/manager.py", line 284, in configure
    cfg(options, config)
  File "/usr/lib/python2.6/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/usr/lib/python2.6/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/usr/lib/python2.6/site-packages/nose/plugins/cover.py", line 137, in configure
    branch=self.coverBranches, data_suffix=None)
TypeError: __init__() got an unexpected keyword argument 'branch'
```

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/213

**Comment by nedbat** [comment]
This appears to be a mismatch between your nose cover plugin, and the version of coverage.py you have installed.  Install the latest coverage.py, and all will be well.
