### ISSUE TITLE
Failing test with current source

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#22]
*Originally reported by* **Anonymous**

----------------------------------------

If I download the current repository and run all the tests, I get one failure:

======================================================================
FAIL: test/farm/run/run_timid.py
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/users/geoff/lib64/python/nose-0.11.0-py2.4.egg/nose/case.py", line 183, in runTest
    self.test(*self.arg)
  File "/users/geoff/bin/coverage.clean/test/test_farm.py", line 67, in __call__
    execfile(self.runpy, glo)
  File "run_timid.py", line 25, in ?
  File "/users/geoff/bin/coverage.clean/test/test_farm.py", line 239, in contains
    assert s in text, "Missing content in %s: %r" % (filename, s)
AssertionError: Missing content in out/showtraceout.txt: 'regular None'
-------------------- >> begin captured stdout << ---------------------
regular coverage.collector.PyTracer
timid coverage.collector.PyTracer

--------------------- >> end captured stdout << ----------------------

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/22

**Comment by nedbat** [comment]
*Original comment by* **Geoff Bache (Bitbucket: [geoffbache](https://bitbucket.org/geoffbache), GitHub: Unknown)**

----------------------------------------

Sorry, forgot to login. I'm the reporter.

**Comment by nedbat** [comment]
From the coveragepy directory, can you run this, and send me the output?

    
    python test\test_farm.py out test\farm\run\run_timid.py
    

I get:

    
    regular None
    timid coverage.collector.PyTracer
    regular coverage.collector.PyTracer
    timid coverage.collector.PyTracer
    

Also, what environment variables have you got set?

**Comment by nedbat** [comment]
Occasionally, this test fails for me, I'm not sure why, but an immediate second test run after cleaning the tree clears it up.  If you are consistently getting this problem, let me know.
