### ISSUE TITLE
"Can't find program" exceptions are shown in an ugly way

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#23]
If you use "coverage run xyzzy.py" and xyzzy.py isn't found, the exception shows stack frames from coverage.py itself:

    
    C:\ned\coverage\trunk> coverage run xyzzy.py
    Traceback (most recent call last):
      File "c:\Python25\Scripts\coverage-script.py", line 8, in <module>
        load_entry_point('coverage==3.0.1', 'console_scripts', 'coverage')()
      File "C:\ned\coverage\trunk\coverage\cmdline.py", line 504, in main
        return CoverageScript().command_line(sys.argv[1:])
      File "C:\ned\coverage\trunk\coverage\cmdline.py", line 388, in command_line
        self.run_python_file(args[0], args)
      File "C:\ned\coverage\trunk\coverage\execfile.py", line 35, in run_python_file
        source = open(filename, 'rU').read()
    IOError: [Errno 2] No such file or directory: 'xyzzy.py'
    

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/23

**Comment by nedbat** [comment]
Fixed in <<changeset [5ae8bd351d4a (bb)](https://bitbucket.org/ned/coveragepy/commits/5ae8bd351d4a)>>

**Comment by nedbat** [comment]
Removing version: 3.0.1 (automated comment)

**Comment by nedbat** [comment]
Add Python 3.5 CI
fixes #23

→ <<cset [4b095cd90ed9 (bb)](https://bitbucket.org/ned/coveragepy/commits/4b095cd90ed9)>>
