### ISSUE TITLE
nested coverage instances causes assertation error

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#296]
*Originally reported by* **space one (Bitbucket: [spaceone](https://bitbucket.org/spaceone), GitHub: [spaceone](https://github.com/spaceone))**

----------------------------------------

```
#!python
from coverage import coverage
c = coverage()
c.start()
c2 = coverage()
c2.stop()
c.stop()
```
causes:
Traceback (most recent call last):
  File "s.py", line 6, in <module>
    c2.stop()
  File "/usr/lib/python2.7/site-packages/coverage/control.py", line 410, in stop
    self.collector.stop()
  File "/usr/lib/python2.7/site-packages/coverage/collector.py", line 294, in stop
    assert self._collectors[-1] is self
AssertionError

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/296

**Comment by nedbat** [comment]
@spaceone Is there a use case here?  Why would you want to run coverage like this?

**Comment by nedbat** [comment]
*Original comment by* **space one (Bitbucket: [spaceone](https://bitbucket.org/spaceone), GitHub: [spaceone](https://github.com/spaceone))**

----------------------------------------

to test the whole project and test only specific tests

**Comment by nedbat** [comment]
I notice now in your code above that you stopped c2 without having ever started it.  When I add `c2.start()` to your sample, it runs without error.   I don't know that you will get the nested behavior you want, but at least it doesn't raise an assertion.

**Comment by nedbat** [comment]
*Original comment by* **space one (Bitbucket: [spaceone](https://bitbucket.org/spaceone), GitHub: [spaceone](https://github.com/spaceone))**

----------------------------------------

oh... thanks...
