### ISSUE TITLE
Reporting on an empty .coverage raises ValueErrror

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#3]
$ coverage -e
    $ coverage -r
    Traceback (most recent call last):
      File "c:\Python25\Scripts\coverage-script.py", line 8, in <module>
        load_entry_point('coverage==3.0b2', 'console_scripts', 'coverage')()
      File "c:\ned\coverage\trunk\coverage\cmdline.py", line 169, in main
        return CoverageScript().command_line(sys.argv[1:])
      File "c:\ned\coverage\trunk\coverage\cmdline.py", line 156, in command_line
        reporter.report(args, omit_prefixes=omit)
      File "c:\ned\coverage\trunk\coverage\summary.py", line 21, in report
        max_name = max(5, max(map(lambda cu: len(cu.name), self.code_units)))
    ValueError: max() arg is an empty sequence
    

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/3

**Comment by nedbat** [comment]
Fixed in <<changeset [2133c70d8fc0 (bb)](https://bitbucket.org/ned/coveragepy/commits/2133c70d8fc0)>>

**Comment by nedbat** [comment]
Removing version: 3.0b2 (automated comment)
