### ISSUE TITLE
Infinite recursion when using cover-html

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#309]
*Originally reported by* **Anonymous**

----------------------------------------

All other coverage output (text, xml) work fine, but when attempting to use cover-html we get stuck in an infinite loop until Python finally gives up.

The line in html.py that causes this is applying the configuration, and I commented that out and re-ran and the report generates successful. I'm not entirely sure how to further debug, but am happy to help in whatever way I can! It's 100% reproducible, so hopefully can provide any other information to help get this resolved.

nose 1.3.3, coverage 3.7.1

Thanks!
-Jay - jshirley@gmail.com

{code}
Traceback (most recent call last):
  File "/Users/jshirley/.virtualenvs/vvv/bin/nosetests", line 9, in <module>
    load_entry_point('nose==1.3.3', 'console_scripts', 'nosetests')()
  File "/Users/jshirley/.virtualenvs/vvv/lib/python2.7/site-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/Users/jshirley/.virtualenvs/vvv/lib/python2.7/site-packages/nose/core.py", line 207, in runTests
    result = self.testRunner.run(self.test)
  File "/Users/jshirley/.virtualenvs/vvv/lib/python2.7/site-packages/nose/core.py", line 66, in run
    result.printErrors()
  File "/Users/jshirley/.virtualenvs/vvv/lib/python2.7/site-packages/nose/result.py", line 110, in printErrors
    self.config.plugins.report(self.stream)
  File "/Users/jshirley/.virtualenvs/vvv/lib/python2.7/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/Users/jshirley/.virtualenvs/vvv/lib/python2.7/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/Users/jshirley/.virtualenvs/vvv/lib/python2.7/site-packages/nose/plugins/cover.py", line 178, in report
    self.coverInstance.html_report(modules, self.coverHtmlDir)
  File "/Users/jshirley/.virtualenvs/vvv/lib/python2.7/site-packages/coverage/control.py", line 662, in html_report
    return reporter.report(morfs)
  File "/Users/jshirley/.virtualenvs/vvv/lib/python2.7/site-packages/coverage/html.py", line 105, in report
    m.update(self.config)
  File "/Users/jshirley/.virtualenvs/vvv/lib/python2.7/site-packages/coverage/misc.py", line 138, in update
    self.update(a)
  File "/Users/jshirley/.virtualenvs/vvv/lib/python2.7/site-packages/coverage/misc.py", line 138, in update
    self.update(a)
{code}

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/309

**Comment by nedbat** [comment]
In email with Jay, he was not able to reproduce the problem.
