### ISSUE TITLE
Cannot use coverage with jython

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#322]
*Originally reported by* **Chris Bannan (Bitbucket: [cmbannan](https://bitbucket.org/cmbannan), GitHub: [cmbannan](https://github.com/cmbannan))**

----------------------------------------

Using the windows installer, there is no coveragepy directory created.
Therefore `python COVERAGEDIR` cannot be used

But, using the bitbucket clone, that directory is created

To use coverage with python, one can run `python -m coverage run sample.py`
There is no equivalent for jython.

However, `jython \coveragepy\__main__.py run sample.py` does work
This seems like it is not what you intended.  

Also, `jython \coveragepy\__main__.py html` fails.  The error is attached.

My environment is

* Coverage.py, version 3.7.1

* Python 2.7

* Jython 2.7b2

* java version "1.7.0_65"
Java(TM) SE Runtime Environment (build 1.7.0_65-b19)
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/322
- This issue had attachments: coverage-stack.txt.  See the [original issue](https://bitbucket.org/ned/coveragepy/issue/322) for details.

**Comment by nedbat** [comment]
I'm not sure what "python COVERAGEDIR" means: where did that come from?  Generally, the problem here is that you have to get coverage installed into your Jython installation.  The windows installer won't know about Jython, so you'll need to do it more manually: untar the source tarball, and use "jython setup.py install".

The HTML issue is known, I should document that.

**Comment by nedbat** [comment]
*Original comment by* **Chris Bannan (Bitbucket: [cmbannan](https://bitbucket.org/cmbannan), GitHub: [cmbannan](https://github.com/cmbannan))**

----------------------------------------

Sorry about the incomplete COVERAGEDIR comment. That is from the Jython coverage instructions.  See section 6.2.1 at http://www.jython.org/devguide/coverage.html

There is a work-around for jython.  It is in the original bug report.
However, It seems wrong.  Relying on that seems foolish as it seems like an undocumented or possibly unsupported feature.

**Comment by nedbat** [comment]
@cmbannan Sorry I've taken so long to get back to this.  I'd like to get back to testing under Jython, so I'm trying to reproduce these problems now.  If you have any more information, I'd be grateful.

**Comment by nedbat** [comment]
*Original comment by* **Loic Dachary (Bitbucket: [dachary](https://bitbucket.org/dachary), GitHub: [dachary](https://github.com/dachary))**

----------------------------------------

I tried to reproduce the problem with jython-2.5.3 on Ubuntu 16.04 but got the following error

```
#!bash

$ jython coverage.py/__main__.py run sample.py 
jython coverage.py/__main__.py run sample.py 
"my" variable $jythonHome masks earlier declaration in same scope at /usr/bin/jython line 15.
Traceback (most recent call last):
  File "coverage.py/__main__.py", line 11, in <module>
    run_globals = runpy.run_module(PKG, run_name='__main__', alter_sys=True)
  File "coverage.py/__main__.py", line 11, in <module>
    run_globals = runpy.run_module(PKG, run_name='__main__', alter_sys=True)
  File "/usr/share/jython/Lib/runpy.py", line 94, in run_module
    return _run_module_code(code, init_globals, run_name,
  File "/usr/share/jython/Lib/runpy.py", line 51, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/share/jython/Lib/runpy.py", line 32, in _run_code
    exec code in run_globals
  File "/tmp/f/coverage.py/coverage/__init__.py", line 11, in <module>
    from coverage.version import __version__, __url__, version_info
  File "/tmp/f/coverage.py/coverage/__init__.py", line 13, in <module>
    from coverage.control import Coverage, process_startup
  File "/tmp/f/coverage.py/coverage/control.py", line 339
SyntaxError: 'with' will become a reserved keyword in Python 2.6
```

**Comment by nedbat** [comment]
*Original comment by* **Loic Dachary (Bitbucket: [dachary](https://bitbucket.org/dachary), GitHub: [dachary](https://github.com/dachary))**

----------------------------------------

See [another coveragepy issue](https://bitbucket.org/ned/coveragepy/issues/120/try-except-and-break-lines-always-reported) for more information on jython support for coveragepy

**Comment by nedbat** [comment]
Also, #551 reports Jython problems that I am trying to fix.  More Jython info is definitely appreciated.

**Comment by nedbat** [comment]
As of [4d9c54230ba7 (bb)](https://bitbucket.org/ned/coveragepy/commits/4d9c54230ba7), I can run "jython -m coverage run myprog.py".

**Comment by nedbat** [comment]
*Original comment by* **Loic Dachary (Bitbucket: [dachary](https://bitbucket.org/dachary), GitHub: [dachary](https://github.com/dachary))**

----------------------------------------

\o/

**Comment by nedbat** [comment]
This was shipping in 4.3.2.
