### ISSUE TITLE
XML Report Chunk Error

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#359]
*Originally reported by* **Justin Poehnelt (Bitbucket: [justinwp](https://bitbucket.org/justinwp), GitHub: [justinwp](https://github.com/justinwp))**

----------------------------------------

Here is what I am running...

```
coverage run --source=gfsad setup.py test
coverage html 
```
Those two work just fine and results are as expected. But when I run:
```
coverage xml
```
I get the following:

```
Traceback (most recent call last):
  File "/Users/justin/venv/GFSAD_VENV/bin/coverage", line 9, in <module>
    load_entry_point('coverage==3.7.1', 'console_scripts', 'coverage')()
  File "/Users/justin/venv/GFSAD_VENV/lib/python2.7/site-packages/coverage/cmdline.py", line 721, in main
    status = CoverageScript().command_line(argv)
  File "/Users/justin/venv/GFSAD_VENV/lib/python2.7/site-packages/coverage/cmdline.py", line 464, in command_line
    total = self.coverage.xml_report(outfile=outfile, **report_args)
  File "/Users/justin/venv/GFSAD_VENV/lib/python2.7/site-packages/coverage/control.py", line 694, in xml_report
    return reporter.report(morfs, outfile=outfile)
  File "/Users/justin/venv/GFSAD_VENV/lib/python2.7/site-packages/coverage/xmlreport.py", line 56, in report
    self.report_files(self.xml_file, morfs)
  File "/Users/justin/venv/GFSAD_VENV/lib/python2.7/site-packages/coverage/report.py", line 84, in report_files
    report_fn(cu, self.coverage._analyze(cu))
  File "/Users/justin/venv/GFSAD_VENV/lib/python2.7/site-packages/coverage/xmlreport.py", line 117, in xml_file
    branch_stats = analysis.branch_stats()
  File "/Users/justin/venv/GFSAD_VENV/lib/python2.7/site-packages/coverage/results.py", line 176, in branch_stats
    exit_counts = self.parser.exit_counts()
  File "/Users/justin/venv/GFSAD_VENV/lib/python2.7/site-packages/coverage/misc.py", line 75, in _wrapped
    setattr(self, attr, fn(self))
  File "/Users/justin/venv/GFSAD_VENV/lib/python2.7/site-packages/coverage/parser.py", line 252, in exit_counts
    for l1, l2 in self.arcs():
  File "/Users/justin/venv/GFSAD_VENV/lib/python2.7/site-packages/coverage/misc.py", line 75, in _wrapped
    setattr(self, attr, fn(self))
  File "/Users/justin/venv/GFSAD_VENV/lib/python2.7/site-packages/coverage/parser.py", line 236, in arcs
    for l1, l2 in self.byte_parser._all_arcs():
  File "/Users/justin/venv/GFSAD_VENV/lib/python2.7/site-packages/coverage/parser.py", line 632, in _all_arcs
    arcs.update(bp._arcs())
  File "/Users/justin/venv/GFSAD_VENV/lib/python2.7/site-packages/coverage/parser.py", line 598, in _arcs
    next_chunk = byte_chunks[ex]
KeyError: 41564
```

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/359

**Comment by nedbat** [comment]
@justinwp Can you provide me a reproducible test case?  Even if it's a repo with your project, or a zip file with your code in it?  I've never seen that error before, and I don't understand what the XML report would be doing that the HTML report would not.

**Comment by nedbat** [comment]
*Original comment by* **Justin Poehnelt (Bitbucket: [justinwp](https://bitbucket.org/justinwp), GitHub: [justinwp](https://github.com/justinwp))**

----------------------------------------

https://github.com/justinwp/croplands

**Comment by nedbat** [comment]
*Original comment by* **Justin Poehnelt (Bitbucket: [justinwp](https://bitbucket.org/justinwp), GitHub: [justinwp](https://github.com/justinwp))**

----------------------------------------

Just cloned it and tried on a fresh install of ubuntu with same result.

**Comment by nedbat** [comment]
Thanks, I can reproduce the issue with this repo.  It's because of gfsad/utils/countries.py, which is an unusual file :)

**Comment by nedbat** [comment]
Fixed in [92bf73c89a4b (bb)](https://bitbucket.org/ned/coveragepy/commits/92bf73c89a4b)

**Comment by nedbat** [comment]
Issue #368 was marked as a duplicate of this issue.

**Comment by nedbat** [comment]
*Original comment by* **Derek Miller (Bitbucket: [20miller10](https://bitbucket.org/20miller10), GitHub: Unknown)**

----------------------------------------

I am still seeing this error even in your 4.0a5 branch (which is the version that has the fix based on the commit above). Any thoughts as to why this would be?

**Comment by nedbat** [comment]
4.0a5 was released on 16 Feb, the day before this fix.

**Comment by nedbat** [comment]
*Original comment by* **Derek Miller (Bitbucket: [20miller10](https://bitbucket.org/20miller10), GitHub: Unknown)**

----------------------------------------

Ahh. Ok thanks for the quick reply. I will keep an eye out for the next release.

**Comment by nedbat** [comment]
*Original comment by* **gpshead (Bitbucket: [gpshead](https://bitbucket.org/gpshead), GitHub: [gpshead](https://github.com/gpshead))**

----------------------------------------

Issue #373 was marked as a duplicate of this issue.

**Comment by nedbat** [comment]
BTW: countries.py has changed, but this is the version that caused the crash: https://github.com/justinwp/croplands/blob/83874e8efd532d2efe324231ec8875377cd9759a/gfsad/utils/countries.py
