### ISSUE TITLE
Broken Python 3.2 support

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#417]
*Originally reported by* **Valentin Lorentz (Bitbucket: [ProgVal](https://bitbucket.org/ProgVal), GitHub: [ProgVal](https://github.com/ProgVal))**

----------------------------------------

Recently (after the release of python-coverage 4.0, I guess), I started getting this traceback with Python 3.2:

```
#!pytb
$ coverage3 run run_tests.py
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.2.5/bin/coverage3", line 9, in <module>
    load_entry_point('coverage==4.0', 'console_scripts', 'coverage3')()
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/pkg_resources/__init__.py", line 519, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/pkg_resources/__init__.py", line 2630, in load_entry_point
    return ep.load()
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/pkg_resources/__init__.py", line 2310, in load
    return self.resolve()
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/pkg_resources/__init__.py", line 2316, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/coverage/__init__.py", line 13, in <module>
    from coverage.control import Coverage, process_startup
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/coverage/control.py", line 14, in <module>
    from coverage.annotate import AnnotateReporter
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/coverage/annotate.py", line 81
    dest.write(u'  ')
                   ^
SyntaxError: invalid syntax
```

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/417

**Comment by nedbat** [comment]
*Original comment by* **Florian Bruhin (Bitbucket: [The-Compiler](https://bitbucket.org/The-Compiler), GitHub: [The-Compiler](https://github.com/The-Compiler))**

----------------------------------------

Python 3.2 support was dropped in 4.0a2 - you'll have to use `coverage==3.7.1` for Python 3.2. See #407 for some other hints as well.

**Comment by nedbat** [comment]
Duplicate of #407.
