### ISSUE TITLE
Python3.5: Failed building wheel for coverage

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#421]
*Originally reported by* **Florian Bruhin (Bitbucket: [The-Compiler](https://bitbucket.org/The-Compiler), GitHub: [The-Compiler](https://github.com/The-Compiler))**

----------------------------------------

When trying to "pip install coverage" in a fresh Python 3.5 virtualenv, I get this:

```
  running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-il02usy1/coverage/setup.py", line 197, in <module>
      main()
    File "/tmp/pip-build-il02usy1/coverage/setup.py", line 187, in main
      setup(**setup_args)
    File "/usr/lib64/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib64/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib64/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/florian/proj/qutebrowser/git/m/.venv35/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 213, in run
      archive_basename = self.get_archive_basename()
    File "/home/florian/proj/qutebrowser/git/m/.venv35/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 161, in get_archive_basename
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/home/florian/proj/qutebrowser/git/m/.venv35/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 155, in get_tag
      assert tag == supported_tags[0]
  AssertionError
  
  ----------------------------------------
  Failed building wheel for coverage
Failed to build coverage
```

It still installs, but I'm guessing without caching a wheel.

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/421

**Comment by nedbat** [comment]
Use a newer version of wheel: https://bitbucket.org/pypa/wheel/issues/146/wheel-building-fails-on-cpython-350b3
