### ISSUE TITLE
Custom encodings prevent reporting

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#451]
Some projects register their own encoding as a way of applying a pre-processor to files.  Cinje is one like this: https://github.com/marrow/cinje/blob/develop/example/bootstrap/page.py
```
# encoding: cinje

: def _sample
	: """A demonstration of how to utilize the page wrapper."""
	
	: def custom_footer *, styles=[], scripts=[]
		: """No jQuery by default on this page, for some reason."""
		
		: for href in scripts
		<script&{src=href}></script>
		: end
	: end
	
	: using page "Hello world!", footer=custom_footer
		
		<p>This is, like, some content or something.</p>
		
	: end
: end
```
When coverage tries to report on this file, it errors out (https://travis-ci.org/marrow/cinje/jobs/94109526#L392-L435 ): 
```
Traceback (most recent call last):
  File "/home/travis/build/marrow/cinje/.tox/py27/bin/coverage", line 11, in <module>
    sys.exit(main())
  File "/home/travis/build/marrow/cinje/.tox/py27/lib/python2.7/site-packages/coverage/cmdline.py", line 741, in main
    status = CoverageScript().command_line(argv)
  File "/home/travis/build/marrow/cinje/.tox/py27/lib/python2.7/site-packages/coverage/cmdline.py", line 514, in command_line
    total = self.coverage.xml_report(outfile=outfile, **report_args)
  File "/home/travis/build/marrow/cinje/.tox/py27/lib/python2.7/site-packages/coverage/control.py", line 1057, in xml_report
    return reporter.report(morfs, outfile=outfile)
  File "/home/travis/build/marrow/cinje/.tox/py27/lib/python2.7/site-packages/coverage/xmlreport.py", line 75, in report
    self.report_files(self.xml_file, morfs)
  File "/home/travis/build/marrow/cinje/.tox/py27/lib/python2.7/site-packages/coverage/report.py", line 75, in report_files
    report_fn(fr, self.coverage._analyze(fr))
  File "/home/travis/build/marrow/cinje/.tox/py27/lib/python2.7/site-packages/coverage/control.py", line 891, in _analyze
    return Analysis(self.data, it)
  File "/home/travis/build/marrow/cinje/.tox/py27/lib/python2.7/site-packages/coverage/results.py", line 19, in __init__
    self.statements = self.file_reporter.lines()
  File "/home/travis/build/marrow/cinje/.tox/py27/lib/python2.7/site-packages/coverage/python.py", line 139, in lines
    self._statements, self._excluded = self.parser.parse_source()
  File "/home/travis/build/marrow/cinje/.tox/py27/lib/python2.7/site-packages/coverage/python.py", line 131, in parser
    exclude=self.coverage._exclude_regex('exclude'),
  File "/home/travis/build/marrow/cinje/.tox/py27/lib/python2.7/site-packages/coverage/parser.py", line 37, in __init__
    self.text = get_python_source(self.filename)
  File "/home/travis/build/marrow/cinje/.tox/py27/lib/python2.7/site-packages/coverage/python.py", line 53, in get_python_source
    source = source.decode(source_encoding(source), "replace")
  File "/home/travis/build/marrow/cinje/.tox/py27/lib/python2.7/site-packages/coverage/phystokens.py", line 238, in _source_encoding_py2
    encoding = find_cookie(first)
  File "/home/travis/build/marrow/cinje/.tox/py27/lib/python2.7/site-packages/coverage/phystokens.py", line 219, in find_cookie
    raise SyntaxError("unknown encoding: " + encoding)
SyntaxError: unknown encoding: cinje
```

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/451

**Comment by nedbat** [comment]
One possibility is to have a setting which is a list of modules to import during the reporting phase.

**Comment by nedbat** [comment]
*Original comment by* **Loic Dachary (Bitbucket: [dachary](https://bitbucket.org/dachary), GitHub: [dachary](https://github.com/dachary))**

----------------------------------------

For the record the proposed fix is at https://bitbucket.org/ned/coveragepy/pull-requests/111/add-import-modules-report-commands-451/diff

**Comment by nedbat** [comment]
*Original comment by* **Loic Dachary (Bitbucket: [dachary](https://bitbucket.org/dachary), GitHub: [dachary](https://github.com/dachary))**

----------------------------------------

Proposed fix, take 2 https://bitbucket.org/ned/coveragepy/pull-requests/115/add-pre_import_modules-to-help-report/diff

**Comment by nedbat** [comment]
I haven't heard about this need in a long time.  If anyone has a new need for it, feel free to open a new issue.
