### ISSUE TITLE
Make it clear Python 3.2 no longer supported

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#462]
*Originally reported by* **hugovk (Bitbucket: [hugovk](https://bitbucket.org/hugovk), GitHub: [hugovk](https://github.com/hugovk))**

----------------------------------------

Rather than an error something like this on Python 3.2:

```
$ coverage erase
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.2.5/bin/coverage", line 9, in <module>
    load_entry_point('coverage==4.0.3', 'console_scripts', 'coverage')()
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/pkg_resources/__init__.py", line 519, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/pkg_resources/__init__.py", line 2630, in load_entry_point
    return ep.load()
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/pkg_resources/__init__.py", line 2310, in load
    return self.resolve()
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/pkg_resources/__init__.py", line 2316, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/coverage/__init__.py", line 13, in <module>
    from coverage.control import Coverage, process_startup
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/coverage/control.py", line 15, in <module>
    from coverage.annotate import AnnotateReporter
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/coverage/annotate.py", line 85
    dest.write(u'  ')
                   ^
SyntaxError: invalid syntax
```

It'd be much more helpful to check the Python version and just exit saying Python 3.2 is no longer supported, and to use something like `pip install coverage==3.7.1` for 3.2.

What do you think?

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/462

**Comment by nedbat** [comment]
This is complicated a bit by the fact that I support PyPy3, which claims to be 3.2, but allows u"" literals.

**Comment by nedbat** [comment]
I've been very clear about the supported versions of Python.  I would rather not add fragile checks to setup.py.  Very few people are using Python 3.2 these days.
