### ISSUE TITLE
Unable to run coverage tool using embedded python using the -m option or when copied to different path locations in windows

### ISSUE THREAD

**Issue by gourish2k** [coveragepy/coveragepy#739]
I am trying to run the python coverage tool using embedded python downloaded from https://www.python.org/ftp/python/3.6.1/python-3.6.1-embed-amd64.zip
The following are the steps I followed to run a test code using coverage module.

1) After downloading python-3.6.1-embed-amd64.zip, I uncompress the files to D:\some_directory\python-3.6.1-embed-amd64

2) cd python-3.6.1-embed-amd64

3) python get-pip.py

4) python -mpip install coverage

5) python-3.6.1-embed-amd64\python36._pth is changed to 

```
    python36.zip
    Lib\site-packages
    .
    # Uncomment to run site.main() automatically
    #import site
```
6) In case if there is an internet proxy to used then use the following command

    SET HTTP_PROXY=http://username:password@proxy_ip:proxy_port

7) python -mpip install coverage

Create test files as follows

The file module_prog.py is as follows

    # -*- coding: utf-8 -*-
    """
        Dummy method for testing
    """

    def method_to_tested() -> None:
        """
        Method To be tested
        """
        print("Called method to be tested")

The file test_module.py is as follows
        
    """ Unit test script for testing File : test_module.py
    """

    import unittest
    from module_prog import method_to_tested

    class TestMethods(unittest.TestCase):
        """ Testing the methods """

        def test_method_to_tested(self):
            method_to_tested()

    if __name__ == "__main__":
        unittest.main(warnings='ignore')

8) I run the following

```
    D:\some_directory\python-3.6.1-embed-amd64>python test_module.py

    Called method to be tested
    .
    ----------------------------------------------------------------------
    Ran 1 test in 0.000s

    OK
```

9) But if I run the instruction as mentioned below using converage I get the following error.

```
    D:\some_directory\python-3.6.1-embed-amd64>python -mcoverage run test_module.py

    Traceback (most recent call last):
      File "test_module.py", line 4, in <module>
        import unittest
    ModuleNotFoundError: No module named 'unittest'
```

If I run the command

      Scripts\converage.exe run test_module.py

Then coverage run successfully,
But if I move the embedded python to another directory and try to run the same command as above then I get the following error

    D:\some_other_directory\python-3.6.1-embed-amd64>Scripts\coverage.exe run test_module.py

    Fatal error in launcher: Unable to create process using 
    '"d:\some_directory\python-3.6.1-embed-amd64\python.exe" "D:\some_other_directory\python-3.6.1-embed-amd64\Scripts\coverage.exe" run test_module.py'

How can I make coverage run as a python module  in case the python is embedded python

**Comment by nedbat** [comment]
It doesn't make sense to me that coverage wouldn't be able to import unittest.

You ask how to make coverage run as a module, but you are already doing that: `python -m coverage`.

Before your "import unittest" line, add this: `import sys, pprint; pprint.pprint(sys.path)`.  Then run it both ways, and let's compare the output.

Also, BTW, you don;'t need to use `unittest.main()` at all, you can run unittest as:  `python -m unittest discover`.

**Comment by gourish2k** [comment]
Thank you for you reply, and sorry for my late reply

I think my question is not clear, let give a more precise explanation
I know as how to run coverage as a module as I have given in the example, but when I try to run it as a module using the embedded python as mentioned above I am getting the error which is specified.

I also forgot to mention that when the original coverage tool installation was done the directory name was `some_directory`, that is python was at location  `d:\some_directory\python-3.6.1-embed-amd64\python.exe` but afterwards I have renamed the directory name to `some_other_directory`, thus the python was at location `D:\some_other_directory\python-3.6.1-embed-amd642`.
The reason why I was doing this because since I am using embedded python I expected that the installed tools and packages should run from any locations from where the embedded python is copied.

If I run the coverage tool when the directory is `some_directory` then the coverage tools runs properly. But not in case when I rename the directory to `some_other_directory`

I have put the line of code ` import sys; print(sys.path)` and following are the results which I get. I did not have pprint in my installation thus I have used the print statement, however let me know if its precisely required so that I can install and use it. Please note that the test is with directory name changed that is `some_other_directory`

case 1, running coverage as a module
```

D:\some_other_directory\python-3.6.1-embed-amd642>python -mcoverage run test_module.py

['D:\\some_other_directory\\python-3.6.1-embed-amd642', 'D:\\some_other_directory\\python-3.6.1-embed-amd642\\Lib\\site-packages', 'D:\\some_other_directory\\python-3.6.1-embed-amd642']
Traceback (most recent call last):
  File "test_module.py", line 4, in <module>
    import unittest
ModuleNotFoundError: No module named 'unittest'
```

case 2, running coverage tool

```
D:\some_other_directory\python-3.6.1-embed-amd642>Scripts\coverage.exe run test_module
.py
Fatal error in launcher: Unable to create process using '"d:\some_directory\python-3.6.1-embed-amd64\python.exe" "D:\some_other_directory\python-3.6.1-embed-amd642\Scripts\coverage.exe" run test_module.py'
```

> Also, BTW, you don;'t need to use unittest.main() at all, you can run unittest as: python -m unittest discover.

Apparently my main objective was to run the coverage tool on the unittest which are already defined, thus I am using the above command `unittest.main()` in the code, but if I use the instruction  `python -m unittest discover` then I may not be able to use the coverage tool.
