### ISSUE TITLE
Problems on latest version - 4.5.2

### ISSUE THREAD

**Issue by paulocoutinhox** [coveragepy/coveragepy#750]
Hi,

Im receiving this errors after update:

![image](https://user-images.githubusercontent.com/395096/50705641-9712fa00-1042-11e9-891e-b4ef60caa04f.png)

Thanks for any help.

**Comment by nedbat** [comment]
Sorry you are having trouble, but you'll have to provide a reproducible scenario before I'd be able to help.  The error message says your current directory doesn't exist.  Does that ring any bells?

**Comment by paulocoutinhox** [comment]
Hi,

Its easy to reproduce:

```
git clone https://github.com/ezored/ezored.git
cd ezored
make install
make test-cov
```

Thanks for any help. It start happen after update to latest version of:

```
testfixtures==6.4.1
pytest==4.0.2
pytest-cov==2.6.0
coverage==4.5.2
```

Thanks again.

**Comment by paulocoutinhox** [comment]
When i put some print inside your code, i got:

```
def set_relative_directory():
    """Set the directory that `relative_filename` will be relative to."""
    global RELATIVE_DIR, CANONICAL_FILENAME_CACHE

    # The absolute path to our current directory.
    print("-------------------------------")
    print("1 - {}".format(os.curdir))
    print("2 - {}".format(abs_file(os.curdir)))
    print("3 - {}".format(os.sep))
    print("4 - {}".format(os.path.normcase(abs_file(os.curdir) + os.sep)))
    print("-------------------------------")
    
    RELATIVE_DIR = os.path.normcase(abs_file(os.curdir) + os.sep)

    # Cache of results of calling the canonical_filename() method, to
    # avoid duplicating work.
    CANONICAL_FILENAME_CACHE = {}

```

Output:

```
------------------------------
1 - .

INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/_pytest/main.py", line 185, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/_pytest/main.py", line 225, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/pluggy/hooks.py", line 284, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/pytest_cov/plugin.py", line 228, in pytest_runtestloop
INTERNALERROR>     self.cov_controller.finish()
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/pytest_cov/engine.py", line 167, in finish
INTERNALERROR>     self.cov.stop()
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/coverage/control.py", line 675, in load
INTERNALERROR>     self._init()
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/coverage/control.py", line 223, in _init
INTERNALERROR>     set_relative_directory()
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/coverage/files.py", line 30, in set_relative_directory
INTERNALERROR>     print("2 - {}".format(abs_file(os.curdir)))
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/coverage/files.py", line 170, in abs_file
INTERNALERROR>     path = os.path.realpath(path)
INTERNALERROR>   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 376, in realpath
INTERNALERROR>     return abspath(path)
INTERNALERROR>   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 364, in abspath
INTERNALERROR>     cwd = os.getcwd()
INTERNALERROR> OSError: [Errno 2] No such file or directory
```

Current dir is returning ".", this is the problem. When line is executed throw the error:

```
abs_file(os.curdir)
```

**Comment by nedbat** [comment]
Thanks, that does reproduce the problem for me.  But I get the same error if I install coverage 4.5, or 4.4, so I don't think the upgrade of coverage.py caused the problem.

[Your commit](https://github.com/ezored/ezored/commit/84ddfeeab211cdcd8b70effbf0229062215ad7f4) also updated pytest-cov.  If I re-install pytest-cov==2.5.1, the problem disappears.  You should report a bug to pytest-cov.
