### ISSUE TITLE
Coverage breaks on Python 2.7

### ISSUE THREAD

**Issue by nedbat** [coveragepy/coveragepy#78]
*Originally reported by* **Domen Kožar (Bitbucket: [iElectric](https://bitbucket.org/iElectric), GitHub: [iElectric](https://github.com/iElectric))**

----------------------------------------

    
    #!python
    
    + ./bin/python2.7 setup.py nosetests --with-xunit --with-xcoverage
    running nosetests
    running egg_info
    writing requirements to repoze.who.plugins.formcookie.egg-info/requires.txt
    writing repoze.who.plugins.formcookie.egg-info/PKG-INFO
    writing namespace_packages to repoze.who.plugins.formcookie.egg-info/namespace_packages.txt
    writing top-level names to repoze.who.plugins.formcookie.egg-info/top_level.txt
    writing dependency_links to repoze.who.plugins.formcookie.egg-info/dependency_links.txt
    writing entry points to repoze.who.plugins.formcookie.egg-info/entry_points.txt
    reading manifest file 'repoze.who.plugins.formcookie.egg-info/SOURCES.txt'
    writing manifest file 'repoze.who.plugins.formcookie.egg-info/SOURCES.txt'
    running build_ext
    ...................
    Traceback (most recent call last):
      File "setup.py", line 32, in <module>
        """,
      File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/var/lib/hudson/home/jobs/repoze.who.plugins.formcookie/workspace/python/2.7/lib/python2.7/site-packages/nose-0.11.4-py2.7.egg/nose/commands.py", line 137, in run
        TestProgram(argv=argv, config=self.__config)
      File "/var/lib/hudson/home/jobs/repoze.who.plugins.formcookie/workspace/python/2.7/lib/python2.7/site-packages/nose-0.11.4-py2.7.egg/nose/core.py", line 117, in __init__
        **extra_args)
      File "/usr/lib/python2.7/unittest/main.py", line 95, in __init__
        self.runTests()
      File "/var/lib/hudson/home/jobs/repoze.who.plugins.formcookie/workspace/python/2.7/lib/python2.7/site-packages/nose-0.11.4-py2.7.egg/nose/core.py", line 196, in runTests
        result = self.testRunner.run(self.test)
      File "/var/lib/hudson/home/jobs/repoze.who.plugins.formcookie/workspace/python/2.7/lib/python2.7/site-packages/nose-0.11.4-py2.7.egg/nose/core.py", line 63, in run
        result.printErrors()
      File "/var/lib/hudson/home/jobs/repoze.who.plugins.formcookie/workspace/python/2.7/lib/python2.7/site-packages/nose-0.11.4-py2.7.egg/nose/result.py", line 110, in printErrors
        self.config.plugins.report(self.stream)
      File "/var/lib/hudson/home/jobs/repoze.who.plugins.formcookie/workspace/python/2.7/lib/python2.7/site-packages/nose-0.11.4-py2.7.egg/nose/plugins/manager.py", line 93, in __call__
        return self.call(*arg, **kw)
      File "/var/lib/hudson/home/jobs/repoze.who.plugins.formcookie/workspace/python/2.7/lib/python2.7/site-packages/nose-0.11.4-py2.7.egg/nose/plugins/manager.py", line 161, in simple
        result = meth(*arg, **kw)
      File "/var/lib/hudson/home/jobs/repoze.who.plugins.formcookie/workspace/python/2.7/lib/python2.7/site-packages/nosexcover-1.0.4-py2.7.egg/nosexcover/nosexcover.py", line 33, in report
        coverage._the_coverage.xml_report(morfs, outfile='coverage.xml')
      File "/var/lib/hudson/home/jobs/repoze.who.plugins.formcookie/workspace/python/2.7/lib/python2.7/site-packages/coverage-3.3.1-py2.7-linux-i686.egg/coverage/control.py", line 390, in xml_report
        morfs, omit_prefixes=self.config.omit_prefixes, outfile=outfile
      File "/var/lib/hudson/home/jobs/repoze.who.plugins.formcookie/workspace/python/2.7/lib/python2.7/site-packages/coverage-3.3.1-py2.7-linux-i686.egg/coverage/xmlreport.py", line 55, in report
        self.report_files(self.xml_file, morfs, omit_prefixes=omit_prefixes)
      File "/var/lib/hudson/home/jobs/repoze.who.plugins.formcookie/workspace/python/2.7/lib/python2.7/site-packages/coverage-3.3.1-py2.7-linux-i686.egg/coverage/report.py", line 57, in report_files
        report_fn(cu, self.coverage._analyze(cu))
      File "/var/lib/hudson/home/jobs/repoze.who.plugins.formcookie/workspace/python/2.7/lib/python2.7/site-packages/coverage-3.3.1-py2.7-linux-i686.egg/coverage/xmlreport.py", line 106, in xml_file
        branch_lines = analysis.branch_lines()
      File "/var/lib/hudson/home/jobs/repoze.who.plugins.formcookie/workspace/python/2.7/lib/python2.7/site-packages/coverage-3.3.1-py2.7-linux-i686.egg/coverage/results.py", line 98, in branch_lines
        exit_counts = self.parser.exit_counts()
      File "/var/lib/hudson/home/jobs/repoze.who.plugins.formcookie/workspace/python/2.7/lib/python2.7/site-packages/coverage-3.3.1-py2.7-linux-i686.egg/coverage/misc.py", line 58, in _wrapped
        setattr(self, attr, fn(self))
      File "/var/lib/hudson/home/jobs/repoze.who.plugins.formcookie/workspace/python/2.7/lib/python2.7/site-packages/coverage-3.3.1-py2.7-linux-i686.egg/coverage/parser.py", line 216, in exit_counts
        for l1, l2 in self.arcs():
      File "/var/lib/hudson/home/jobs/repoze.who.plugins.formcookie/workspace/python/2.7/lib/python2.7/site-packages/coverage-3.3.1-py2.7-linux-i686.egg/coverage/misc.py", line 58, in _wrapped
        setattr(self, attr, fn(self))
      File "/var/lib/hudson/home/jobs/repoze.who.plugins.formcookie/workspace/python/2.7/lib/python2.7/site-packages/coverage-3.3.1-py2.7-linux-i686.egg/coverage/parser.py", line 200, in arcs
        for l1, l2 in self.byte_parser._all_arcs():
      File "/var/lib/hudson/home/jobs/repoze.who.plugins.formcookie/workspace/python/2.7/lib/python2.7/site-packages/coverage-3.3.1-py2.7-linux-i686.egg/coverage/parser.py", line 586, in _all_arcs
        arcs.update(bp._arcs())
      File "/var/lib/hudson/home/jobs/repoze.who.plugins.formcookie/workspace/python/2.7/lib/python2.7/site-packages/coverage-3.3.1-py2.7-linux-i686.egg/coverage/parser.py", line 505, in _arcs
        chunks = self._split_into_chunks()
      File "/var/lib/hudson/home/jobs/repoze.who.plugins.formcookie/workspace/python/2.7/lib/python2.7/site-packages/coverage-3.3.1-py2.7-linux-i686.egg/coverage/parser.py", line 443, in _split_into_chunks
        block_stack.pop()
    IndexError: pop from empty list
    

----------------------------------------
- Bitbucket: https://bitbucket.org/ned/coveragepy/issue/78

**Comment by nedbat** [comment]
This is fixed on the trunk (as of <<changeset [107c0d6d3e27 (bb)](https://bitbucket.org/ned/coveragepy/commits/107c0d6d3e27)>>).

Duplicate of #76.

**Comment by nedbat** [comment]
*Original comment by* **Domen Kožar (Bitbucket: [iElectric](https://bitbucket.org/iElectric), GitHub: [iElectric](https://github.com/iElectric))**

----------------------------------------

Ah ok, waiting for release then:) Thanks!

**Comment by nedbat** [comment]
No need to wait, feel free to grab a copy of the repo.

**Comment by nedbat** [comment]
*Original comment by* **Erik Allik (Bitbucket: [eallik](https://bitbucket.org/eallik), GitHub: [eallik](https://github.com/eallik))**

----------------------------------------

Just installed the tip, and still getting the error. It was working, and suddenly stopped. Any quick workarounds?
