### ISSUE TITLE
variable type annotation raises "SyntaxError: invalid syntax"

### ISSUE THREAD

**Issue by LaMonF** [coveragepy/coveragepy#830]
**Describe the bug**
When using type annotation for variables asignment, coverage raises a `SyntaxError: invalid syntax `

**To Reproduce**
How can we reproduce the problem? 
1. What version of Python are you running : 3.5, 3.6
2. What versions of what packages do you have installed? coverage==4.5.4
3. What code are you running?  
```python
import unittest
class Testme(unittest.TestCase):
	age: int = 5
```
4. What commands did you run?
```sh
~/test_project_path/: coverage run -m unittest discover
>>
File "path/test/testme.py", line 3
    age: int = 5
       ^
SyntaxError: invalid syntax
```

**Expected behavior**
No error thrown

**Additional context**
Nope

**Comment by nedbat** [comment]
Variable annotation syntax is invalid in Python 3.5.  Try running it without coverage: it will still be a syntax error:
```
$ python3.5 -m unittest discover
E
======================================================================
ERROR: test_it (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_it
Traceback (most recent call last):
  File "/usr/local/pythonz/pythons/CPython-3.5.5/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/pythonz/pythons/CPython-3.5.5/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/private/tmp/bug830/test_it.py", line 3
    age: int = 5
       ^
SyntaxError: invalid syntax


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```
