### ISSUE TITLE
Disable SQLite Support

### ISSUE THREAD

**Issue by mikegrima** [coveragepy/coveragepy#889]
Hello!

Is there a way to disable SQLite support for coverage 5.0? Coverage 5.0 recently broke tests in [moto](https://github.com/spulec/moto) where, for some reason, it does not play nicely with the AWS X-Ray Client: https://github.com/aws/aws-xray-sdk-python

Here is a stacktrace showcasing the error:
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.8.0/bin/nosetests", line 8, in <module>
    sys.exit(run_exit())
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/nose/core.py", line 118, in __init__
    unittest.TestProgram.__init__(
  File "/opt/python/3.8.0/lib/python3.8/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/nose/core.py", line 207, in runTests
    result = self.testRunner.run(self.test)
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/nose/core.py", line 66, in run
    result.printErrors()
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/nose/result.py", line 110, in printErrors
    self.config.plugins.report(self.stream)
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/nose/plugins/cover.py", line 183, in report
    self.coverInstance.stop()
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/coverage/control.py", line 641, in combine
    self.get_data()
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/coverage/control.py", line 667, in get_data
    if self._collector and self._collector.flush_data():
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/coverage/collector.py", line 429, in flush_data
    self.covdata.add_lines(self.mapped_file_dict(self.data))
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/coverage/sqldata.py", line 436, in add_lines
    self._choose_lines_or_arcs(lines=True)
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/coverage/sqldata.py", line 493, in _choose_lines_or_arcs
    with self._connect() as con:
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/coverage/sqldata.py", line 1008, in __enter__
    self._connect()
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/coverage/sqldata.py", line 996, in _connect
    self.execute("pragma journal_mode=off").close()
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/coverage/sqldata.py", line 1025, in execute
    return self.con.execute(sql, parameters)
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/aws_xray_sdk/ext/sqlite3/patch.py", line 32, in execute
    return self.cursor().execute(*args, **kwargs)
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/aws_xray_sdk/core/models/subsegment.py", line 54, in __call__
    return self.recorder.record_subsegment(
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/aws_xray_sdk/core/recorder.py", line 417, in record_subsegment
    subsegment = self.begin_subsegment(name, namespace)
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/aws_xray_sdk/core/recorder.py", line 284, in begin_subsegment
    segment = self.current_segment()
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/aws_xray_sdk/core/recorder.py", line 267, in current_segment
    entity = self.get_trace_entity()
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/aws_xray_sdk/core/recorder.py", line 369, in get_trace_entity
    return self.context.get_trace_entity()
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/aws_xray_sdk/core/context.py", line 93, in get_trace_entity
    return self.handle_context_missing()
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/aws_xray_sdk/core/context.py", line 118, in handle_context_missing
    raise SegmentNotFoundException(MISSING_SEGMENT_MSG)
aws_xray_sdk.core.exceptions.exceptions.SegmentNotFoundException: cannot find the current segment/subsegment, please make sure you have a segment open
```

The X-Ray client's use of SQLite and coverage's use of the SQLite seem to be stepping over each other. This problem appears on all Python 2 and 3 versions. 

In the meantime, I am going to pin `moto` to `coverage==4.5.4`.

I also raised this issue: https://github.com/spulec/moto/issues/2638

**Comment by nedbat** [comment]
There is no way to disable SQLite in coverage 5.0.  I'd like to understand why this error is happening. If there's something I'm doing wrong with SQLite, I'd like to fix it.

Can you give me specific instructions for reproducing the problem?

**Comment by mikegrima** [comment]
To be honest, I'm not terribly familiar with the AWS X-Ray client.

To reproduce, I ran `nosetests tests/test_xray`. What's odd is, if I'm in the directory (`moto/tests/test_xray`) when I run the tests things are fine. It only errors when running the tests from the `moto` directory.

It's also entirely possible that this is a bug with the AWS X-Ray Client library.

**Comment by mikegrima** [comment]
It looks like it's failing there too: https://travis-ci.org/aws/aws-xray-sdk-python/jobs/625806818

Same stacktrace:
```
No handlers could be found for logger "aws_xray_sdk.core.context"
Traceback (most recent call last):
  File "/home/travis/build/aws/aws-xray-sdk-python/.tox/py27/bin/coverage", line 11, in <module>
    sys.exit(main())
  File "/home/travis/build/aws/aws-xray-sdk-python/.tox/py27/lib/python2.7/site-packages/coverage/cmdline.py", line 824, in main
    status = CoverageScript().command_line(argv)
  File "/home/travis/build/aws/aws-xray-sdk-python/.tox/py27/lib/python2.7/site-packages/coverage/cmdline.py", line 555, in command_line
    return self.do_run(options, args)
  File "/home/travis/build/aws/aws-xray-sdk-python/.tox/py27/lib/python2.7/site-packages/coverage/cmdline.py", line 710, in do_run
    self.coverage.save()
  File "/home/travis/build/aws/aws-xray-sdk-python/.tox/py27/lib/python2.7/site-packages/coverage/control.py", line 613, in save
    data = self.get_data()
  File "/home/travis/build/aws/aws-xray-sdk-python/.tox/py27/lib/python2.7/site-packages/coverage/control.py", line 667, in get_data
    if self._collector and self._collector.flush_data():
  File "/home/travis/build/aws/aws-xray-sdk-python/.tox/py27/lib/python2.7/site-packages/coverage/collector.py", line 429, in flush_data
    self.covdata.add_lines(self.mapped_file_dict(self.data))
  File "/home/travis/build/aws/aws-xray-sdk-python/.tox/py27/lib/python2.7/site-packages/coverage/sqldata.py", line 436, in add_lines
    self._choose_lines_or_arcs(lines=True)
  File "/home/travis/build/aws/aws-xray-sdk-python/.tox/py27/lib/python2.7/site-packages/coverage/sqldata.py", line 493, in _choose_lines_or_arcs
    with self._connect() as con:
  File "/home/travis/build/aws/aws-xray-sdk-python/.tox/py27/lib/python2.7/site-packages/coverage/sqldata.py", line 298, in _connect
    self._create_db()
  File "/home/travis/build/aws/aws-xray-sdk-python/.tox/py27/lib/python2.7/site-packages/coverage/sqldata.py", line 247, in _create_db
    with db:
  File "/home/travis/build/aws/aws-xray-sdk-python/.tox/py27/lib/python2.7/site-packages/coverage/sqldata.py", line 1008, in __enter__
    self._connect()
  File "/home/travis/build/aws/aws-xray-sdk-python/.tox/py27/lib/python2.7/site-packages/coverage/sqldata.py", line 996, in _connect
    self.execute("pragma journal_mode=off").close()
  File "/home/travis/build/aws/aws-xray-sdk-python/.tox/py27/lib/python2.7/site-packages/coverage/sqldata.py", line 1025, in execute
    return self.con.execute(sql, parameters)
  File "/home/travis/build/aws/aws-xray-sdk-python/aws_xray_sdk/ext/sqlite3/patch.py", line 32, in execute
    return self.cursor().execute(*args, **kwargs)
  File "/home/travis/build/aws/aws-xray-sdk-python/aws_xray_sdk/core/models/subsegment.py", line 58, in __call__
    meta_processor=None,
  File "/home/travis/build/aws/aws-xray-sdk-python/aws_xray_sdk/core/recorder.py", line 417, in record_subsegment
    subsegment = self.begin_subsegment(name, namespace)
  File "/home/travis/build/aws/aws-xray-sdk-python/aws_xray_sdk/core/recorder.py", line 284, in begin_subsegment
    segment = self.current_segment()
  File "/home/travis/build/aws/aws-xray-sdk-python/aws_xray_sdk/core/recorder.py", line 267, in current_segment
    entity = self.get_trace_entity()
  File "/home/travis/build/aws/aws-xray-sdk-python/aws_xray_sdk/core/recorder.py", line 369, in get_trace_entity
    return self.context.get_trace_entity()
  File "/home/travis/build/aws/aws-xray-sdk-python/aws_xray_sdk/core/context.py", line 93, in get_trace_entity
    return self.handle_context_missing()
  File "/home/travis/build/aws/aws-xray-sdk-python/aws_xray_sdk/core/context.py", line 118, in handle_context_missing
    raise SegmentNotFoundException(MISSING_SEGMENT_MSG)
aws_xray_sdk.core.exceptions.exceptions.SegmentNotFoundException: cannot find the current segment/subsegment, please make sure you have a segment open
```

**Comment by patti-c** [comment]
I was able to resolve this in my own project by pinning `coverage` in test-requirements.txt back to 4.5.4.

The error we encountered was:

```
INTERNALERROR>     raise CoverageException("Couldn't use data file {!r}: {}".format(self.filename, exc))
INTERNALERROR> coverage.misc.CoverageException: Couldn't use data file 'my_path/.coverage': Safety level may not be changed inside a transaction
```

**Comment by nedbat** [comment]
@patti-c Your error message seems to be different than the top of the issue.  If you open a new issue with specific instructions about how I can reproduce the problem, that would be really helpful.  Thanks.

**Comment by chanchiem** [comment]
Hey,

I'm working on reproducing the issue on the X-Ray side of things. What changes were recently introduced since version 5.0? We'd like to reproduce this reliably and get to the root cause of this as it's breaking our tests at the moment.

**Comment by nedbat** [comment]
@chanchiem The biggest change, and the one that seems implicated here, is that the data file has been changed from a JSON file to a SQLite database.  But I don't see how my use of SQLite and X-Ray's can be conflicting.  More details about 5.0 are here: https://coverage.readthedocs.io/en/coverage-5.0/whatsnew5x.html

**Comment by chanchiem** [comment]
Okay that makes sense. I see what's going on now. What I think is happening is that with the X-Ray sqlite test, it patches the sqlite3 package, and when coverage creates a client to store/query data, no segment exists (this portion is usually created by X-Ray [here](https://github.com/aws/aws-xray-sdk-python/blob/master/tests/ext/sqlite3/test_sqlite3.py#L22)) and then breaks. This must all be happening within the same python instance. We'll do some investigation on our end to see what we can do to fix this issue, but as it is right now, it looks like it's an X-Ray issue.

**Comment by mikegrima** [comment]
I'm going to close this out as it's not a bug with coverage.

**Comment by nedbat** [comment]
Keep me posted.  There is probably something I can do in coverage.py to isolate it from this sort of patching, though ideally the patching would be done in a less pervasive way.

**Comment by Suzi-Clark** [comment]
It doesn't seem like there's any plans to fix things [here](https://github.com/aws/aws-xray-sdk-python/issues/196), I'm aware this issue has been closed for years but just thought I'd cheekily ask if there's any chance of it being revisited on your side? Thanks!

**Comment by nedbat** [comment]
@Suzi-Clark I know nothing about the X-Ray SDK, or why it would interfere with a module that ships with Python.  Can you provide more details?  Wouldn't this break any program using SQLite?
